/**
 * SpatialGrid — circular working area with a clipped square Cartesian overlay.
 *
 * Characters, Props, and Cameras share this geometry. The Atlas image is never
 * baked, scaled, rotated, or regenerated by the grid.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CameraFovCone } from "./CameraFovCone";
import { CameraMarker } from "./CameraMarker";
import {
  CARDINAL_LABELS,
  cellCenterNormalized,
  densityForScale,
  isValidCell,
  normalizedToPixel,
  pointerToCell,
  type GridScale,
} from "./gridGeometry";
import { SLOT_COLORS } from "./types";
import type { SpatialCamera, SpatialCharacterPlacement, SpatialPropPlacement, SlotColorKey } from "./types";

export type GridPlacement = {
  id: string;
  tag: string;
  colorKey: SlotColorKey;
  gridRow: number;
  gridColumn: number;
  normalizedX?: number | null;
  normalizedY?: number | null;
  slotIndex: number;
  kind: "character" | "prop";
};

type Props = {
  backgroundAssetId: string;
  imageUrl: string;
  placements: GridPlacement[];
  cameras: SpatialCamera[];
  selectedPlacementId: string | null;
  selectedCameraId: string | null;
  occupiedMessage: string | null;
  gridScale: GridScale;
  placementActive: boolean;
  onCellClick: (column: number, row: number) => void;
  onSelectPlacement: (placementId: string | null) => void;
  onSelectCamera: (cameraId: string | null) => void;
};

export function toGridPlacements(
  characters: SpatialCharacterPlacement[],
  props: SpatialPropPlacement[],
): GridPlacement[] {
  return [
    ...characters.map((c) => ({
      id: c.id,
      tag: c.tag || c.label,
      colorKey: (c.colorKey as SlotColorKey) || "red",
      gridRow: c.gridRow,
      gridColumn: c.gridColumn,
      normalizedX: c.normalizedX,
      normalizedY: c.normalizedY,
      slotIndex: c.slotIndex,
      kind: "character" as const,
    })),
    ...props.map((p) => ({
      id: p.id,
      tag: p.tag || p.label,
      colorKey: (p.colorKey as SlotColorKey) || "purple",
      gridRow: p.gridRow,
      gridColumn: p.gridColumn,
      normalizedX: p.normalizedX,
      normalizedY: p.normalizedY,
      slotIndex: p.slotIndex,
      kind: "prop" as const,
    })),
  ];
}

function markerPosition(
  gridColumn: number,
  gridRow: number,
  normalizedX: number | null | undefined,
  normalizedY: number | null | undefined,
  density: number,
  size: number,
): { px: number; py: number } | null {
  if (typeof normalizedX === "number" && typeof normalizedY === "number") {
    return normalizedToPixel(normalizedX, normalizedY, size);
  }
  if (gridColumn >= 0 && gridRow >= 0 && isValidCell(gridColumn, gridRow, density)) {
    const center = cellCenterNormalized(gridColumn, gridRow, density);
    return normalizedToPixel(center.x, center.y, size);
  }
  return null;
}

export function SpatialGrid({
  imageUrl,
  placements,
  cameras,
  selectedPlacementId,
  selectedCameraId,
  occupiedMessage,
  gridScale,
  placementActive,
  onCellClick,
  onSelectPlacement,
  onSelectCamera,
}: Props) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState(512);
  const [hover, setHover] = useState<{ column: number; row: number } | null>(null);

  useEffect(() => {
    const ro = new ResizeObserver((entries) => {
      for (const entry of entries) {
        const s = Math.min(entry.contentRect.width, entry.contentRect.height);
        if (s > 0) setSize(s);
      }
    });
    if (containerRef.current) ro.observe(containerRef.current);
    return () => ro.disconnect();
  }, []);

  const density = densityForScale(gridScale);
  const cellPx = size / density;
  const markerSize = Math.max(10, Math.round(cellPx * 0.72));
  const cameraSize = Math.round(markerSize * 0.68);
  const center = size / 2;
  const radius = size / 2 - 1;
  const clipId = "spatial-map-circle-clip";

  const gridPath = useMemo(() => {
    const parts: string[] = [];
    for (let i = 0; i <= density; i += 1) {
      const pos = (i / density) * size;
      parts.push(`M 0 ${pos} H ${size}`);
      parts.push(`M ${pos} 0 V ${size}`);
    }
    return parts.join(" ");
  }, [density, size]);

  const handlePointer = useCallback(
    (clientX: number, clientY: number) => {
      if (!containerRef.current) return null;
      const rect = containerRef.current.getBoundingClientRect();
      return pointerToCell(clientX - rect.left, clientY - rect.top, size, density);
    },
    [density, size],
  );

  const handleClick = useCallback(
    (e: React.MouseEvent<SVGSVGElement>) => {
      const cell = handlePointer(e.clientX, e.clientY);
      if (!cell) return;
      onCellClick(cell.column, cell.row);
    },
    [handlePointer, onCellClick],
  );

  const handleMouseMove = useCallback(
    (e: React.MouseEvent<SVGSVGElement>) => {
      if (!placementActive) {
        setHover(null);
        return;
      }
      setHover(handlePointer(e.clientX, e.clientY));
    },
    [handlePointer, placementActive],
  );

  const hasNormalized = (x: number | null | undefined, y: number | null | undefined) =>
    typeof x === "number" && typeof y === "number";
  const placedPlacements = placements.filter(
    (p) => hasNormalized(p.normalizedX, p.normalizedY) || (p.gridRow >= 0 && p.gridColumn >= 0),
  );
  const placedCameras = cameras.filter(
    (c) => hasNormalized(c.normalizedX, c.normalizedY) || (c.gridRow >= 0 && c.gridColumn >= 0),
  );

  const hoverCenter = hover ? cellCenterNormalized(hover.column, hover.row, density) : null;
  const hoverPx = hoverCenter ? normalizedToPixel(hoverCenter.x, hoverCenter.y, size) : null;

  return (
    <div className="spatial-map__grid-wrap spatial-map__grid-wrap--circle" ref={containerRef}>
      <svg
        className="spatial-map__grid-svg"
        viewBox={`0 0 ${size} ${size}`}
        onClick={handleClick}
        onMouseMove={handleMouseMove}
        onMouseLeave={() => setHover(null)}
        role="img"
        aria-label="Circular spatial map with square placement grid"
        data-testid="spatial-map-grid"
        data-grid-detail={gridScale}
        data-grid-size={density}
        data-grid-kind="cartesian"
      >
        <defs>
          <clipPath id={clipId}>
            <circle cx={center} cy={center} r={radius} />
          </clipPath>
        </defs>

        <g clipPath={`url(#${clipId})`}>
          <image href={imageUrl} x="0" y="0" width={size} height={size} preserveAspectRatio="xMidYMid slice" />
          <path d={gridPath} className="spatial-map__grid-lines" />

          {placementActive && hover && hoverPx ? (
            <rect
              x={hover.column * cellPx}
              y={hover.row * cellPx}
              width={cellPx}
              height={cellPx}
              className="spatial-map__hover-cell"
              data-testid="spatial-map-hover-cell"
            />
          ) : null}

          {placedCameras.map((c) => {
            const px = markerPosition(c.gridColumn, c.gridRow, c.normalizedX, c.normalizedY, density, size);
            if (!px) return null;
            const isSelected = selectedCameraId === c.id;
            return (
              <g
                key={`fov-${c.id}`}
                transform={`translate(${px.px}, ${px.py})`}
                className="spatial-map__fov-layer"
              >
                <CameraFovCone
                  orientation={c.orientation || "N"}
                  fovPreset={c.fovPreset || "medium"}
                  radius={Math.max(cameraSize * 2.6, cellPx * 1.6)}
                  selected={isSelected}
                />
              </g>
            );
          })}

          {placedPlacements.map((p) => {
            const px = markerPosition(p.gridColumn, p.gridRow, p.normalizedX, p.normalizedY, density, size);
            if (!px) return null;
            const isSelected = selectedPlacementId === p.id;
            const footprint = p.kind === "prop" ? markerSize * 0.9 : markerSize;
            const initial = (p.tag || "?").replace(/^[@#]/, "").slice(0, 2);
            return (
              <g
                key={p.id}
                className={`spatial-map__marker${isSelected ? " is-selected" : ""}`}
                transform={`translate(${px.px}, ${px.py})`}
                onClick={(e) => {
                  e.stopPropagation();
                  onSelectPlacement(isSelected ? null : p.id);
                }}
                style={{ cursor: "pointer" }}
                data-testid={`placement-marker-${p.id}`}
                data-kind={p.kind}
              >
                <rect
                  x={-footprint / 2}
                  y={-footprint / 2}
                  width={footprint}
                  height={footprint}
                  rx={2}
                  fill={SLOT_COLORS[p.colorKey] || "#fff"}
                  stroke="rgba(255,255,255,0.85)"
                  strokeWidth={2}
                />
                <text
                  textAnchor="middle"
                  dominantBaseline="middle"
                  fontSize={Math.max(8, footprint * 0.38)}
                  fill="#fff"
                  fontWeight={700}
                >
                  {initial}
                </text>
              </g>
            );
          })}

          {placedCameras.map((c) => {
            const px = markerPosition(c.gridColumn, c.gridRow, c.normalizedX, c.normalizedY, density, size);
            if (!px) return null;
            const isSelected = selectedCameraId === c.id;
            return (
              <g
                key={c.id}
                className={`spatial-map__camera${isSelected ? " is-selected" : ""}`}
                transform={`translate(${px.px}, ${px.py})`}
                onClick={(e) => {
                  e.stopPropagation();
                  onSelectCamera(isSelected ? null : c.id);
                }}
                style={{ cursor: "pointer" }}
                data-testid={`camera-marker-${c.id}`}
              >
                <CameraMarker
                  size={cameraSize}
                  label={c.cameraSlot >= 0 ? `C${c.cameraSlot + 1}` : c.label}
                  orientation={c.orientation || "N"}
                />
                <rect
                  className="spatial-map__camera-hitbox"
                  x={-cameraSize / 2}
                  y={-cameraSize / 2}
                  width={cameraSize}
                  height={cameraSize}
                  fill="transparent"
                  pointerEvents="all"
                />
              </g>
            );
          })}
        </g>

        <circle cx={center} cy={center} r={radius} className="spatial-map__circle-stroke" />

        {CARDINAL_LABELS.map((label, index) => {
          const angle = (index / 8) * Math.PI * 2 - Math.PI / 2;
          const lx = center + (radius - 16) * Math.cos(angle);
          const ly = center + (radius - 16) * Math.sin(angle);
          return (
            <text key={label} x={lx} y={ly} className="spatial-map__grid-label" textAnchor="middle" dominantBaseline="middle">
              {label}
            </text>
          );
        })}
      </svg>

      {occupiedMessage ? <p className="spatial-map__occupied-message">{occupiedMessage}</p> : null}
    </div>
  );
}
