import type { PromptPreset } from "./types";

export const LENS_PRESETS: PromptPreset[] = [
  { id: "14mm", category: "Lens", label: "14mm", fov: 114, look: "extreme width and exaggerated foreground scale", description: "Ultra-wide view with exaggerated foreground scale and a deep, enveloping sense of place.", promptFragment: "Photographed on a 14mm cinematic lens, with extreme width, exaggerated foreground scale, and a deep enveloping sense of place." },
  { id: "18mm", category: "Lens", label: "18mm", fov: 100, look: "broad environmental coverage and strong near-to-far separation", description: "Very wide coverage that still keeps architecture and landscape readable.", promptFragment: "Photographed on an 18mm cinematic lens, with broad environmental coverage and strong separation from foreground to background." },
  { id: "21mm", category: "Lens", label: "21mm", fov: 91, look: "wide spatial depth without extreme distortion", description: "Wide cinematic perspective with spacious depth and controlled edge stretch.", promptFragment: "Photographed on a 21mm cinematic lens, with wide spatial depth and controlled edge stretch." },
  { id: "24mm", category: "Lens", label: "24mm", fov: 84, look: "pronounced spatial depth and broad environmental coverage", description: "Wide cinematic perspective with pronounced spatial depth, broad environmental coverage, and greater separation between foreground and background.", promptFragment: "Photographed on a 24mm cinematic lens, with pronounced spatial depth, broad environmental coverage, and greater separation between foreground and background." },
  { id: "28mm", category: "Lens", label: "28mm", fov: 75, look: "natural wide coverage and comfortable room around the subject", description: "A practical wide lens with room around the subject and modest perspective stretch.", promptFragment: "Photographed on a 28mm cinematic lens, with natural wide coverage and comfortable room around the subject." },
  { id: "35mm", category: "Lens", label: "35mm", fov: 63, look: "storytelling width and believable human perspective", description: "The classic storytelling width, wide enough for place and close enough for performance.", promptFragment: "Photographed on a 35mm cinematic lens, with storytelling width and a believable human perspective." },
  { id: "40mm", category: "Lens", label: "40mm", fov: 57, look: "slightly wide naturalism and quiet presence", description: "A slightly wide natural lens that feels present without calling attention to itself.", promptFragment: "Photographed on a 40mm cinematic lens, with slightly wide naturalism and a quiet sense of presence." },
  { id: "50mm", category: "Lens", label: "50mm", fov: 47, look: "balanced spatial compression close to normal human vision", description: "Natural cinematic perspective with balanced spatial compression and framing close to normal human visual perception.", promptFragment: "Photographed on a 50mm cinematic lens, with balanced spatial compression and framing close to normal human visual perception." },
  { id: "65mm", category: "Lens", label: "65mm", fov: 37, look: "gentle compression and a more intimate field", description: "A short telephoto that begins to simplify the background and draw the subject forward.", promptFragment: "Photographed on a 65mm cinematic lens, with gentle compression and a more intimate field of view." },
  { id: "75mm", category: "Lens", label: "75mm", fov: 32, look: "flattering compression and softened background separation", description: "Portrait-leaning compression with a softened background and natural facial proportions.", promptFragment: "Photographed on a 75mm cinematic lens, with flattering compression and softened background separation." },
  { id: "85mm", category: "Lens", label: "85mm", fov: 28, look: "gentle perspective compression, strong subject isolation, and intimate facial emphasis", description: "Compressed portrait perspective with shallow visual depth, strong subject isolation, and flattering facial proportions.", promptFragment: "Photographed on an 85mm cinematic lens, with gentle perspective compression, strong subject isolation, and intimate facial emphasis." },
  { id: "100mm", category: "Lens", label: "100mm", fov: 24, look: "tighter compression and a quieter background", description: "A longer portrait lens that stacks the background and isolates the subject cleanly.", promptFragment: "Photographed on a 100mm cinematic lens, with tighter compression and a quieter, stacked background." },
  { id: "135mm", category: "Lens", label: "135mm", fov: 18, look: "strong compression and distant subject isolation", description: "Telephoto compression that brings distant subjects forward and flattens space.", promptFragment: "Photographed on a 135mm cinematic lens, with strong compression and distant subject isolation." },
  { id: "200mm", category: "Lens", label: "200mm", fov: 12, look: "extreme compression and a narrow, stacked background", description: "Long-lens compression with a narrow field, stacked planes, and a subject lifted out of the place.", promptFragment: "Photographed on a 200mm cinematic lens, with extreme compression and a narrow, stacked background." },
];
