import type { PromptPreset } from "./types";

export const SCENE_PRESETS: PromptPreset[] = [
  { id: "action", category: "Live Action", label: "Action", description: "Physical momentum and readable geography.", promptFragment: "Action-cinema presentation with clear physical geography, urgent forward momentum, crisp impact, and energetic but readable camera movement." },
  { id: "classic-film", category: "Live Action", label: "Classic Film", description: "Studio-era polish and measured staging.", promptFragment: "Classic studio-film presentation with measured staging, polished light, deliberate performances, and composed theatrical framing." },
  { id: "comedy", category: "Live Action", label: "Comedy", description: "Bright timing and readable faces.", promptFragment: "Comedy presentation with bright, readable faces, generous timing, playful framing, and a light cinematic touch." },
  { id: "scifi-fantasy", category: "Live Action", label: "Sci-Fi / Fantasy", description: "Designed worlds that still feel photographed.", promptFragment: "Science-fiction and fantasy presentation with designed worlds, photographic realism, atmospheric scale, and cinematic light that still feels captured on a lens." },
  { id: "drama", category: "Live Action", label: "Drama", description: "Intimate performance and restrained craft.", promptFragment: "Dramatic presentation with intimate performance, restrained color, natural light falloff, and composition that leaves room for emotion." },
  { id: "epic", category: "Live Action", label: "Epic", description: "Monumental scale and theatrical light.", promptFragment: "Grand epic cinematic presentation emphasizing monumental scale, dramatic depth, sweeping composition, powerful environmental atmosphere, and theatrical lighting." },
  { id: "film-noir", category: "Live Action", label: "Film Noir", description: "Shadow, contrast, and suspense.", promptFragment: "Classic film-noir cinematography with dramatic contrast, sculpted shadow, atmospheric depth, restrained monochromatic tonality, and suspenseful cinematic composition." },
  { id: "horror", category: "Live Action", label: "Horror", description: "Negative space and uneasy light.", promptFragment: "Horror presentation with uneasy negative space, selective light, restrained color, and composition that withholds as much as it reveals." },
  { id: "realistic-anime", category: "Anime / Animation", label: "Realistic Anime", description: "Dimensional anime with film lighting.", promptFragment: "Realistic anime cinematic presentation with detailed environments, natural dimensional lighting, expressive character rendering, refined textures, and film-quality composition." },
  { id: "classic-anime", category: "Anime / Animation", label: "Classic Anime", description: "Cel-shaded staging and graphic color.", promptFragment: "Classic anime presentation with clean cel-shaded forms, graphic color, expressive poses, and cinematic staging." },
  { id: "two-five-d", category: "Anime / Animation", label: "2.5D Animation", description: "Drawn characters in a dimensional space.", promptFragment: "2.5D animated presentation with illustrated characters set in dimensional space, layered depth, and cinematic lighting." },
  { id: "cinematic-3d", category: "Anime / Animation", label: "3D Animation", description: "Feature-animation volume and appeal.", promptFragment: "Cinematic 3D animation with appealing volumes, rich material response, soft dimensional light, and feature-film composition." },
  { id: "claymation", category: "Anime / Animation", label: "Claymation", description: "Handmade texture and tactile sets.", promptFragment: "Claymation presentation with handmade surface texture, tactile sets, gentle practical light, and the charm of a photographed miniature." },
  { id: "documentary", category: "Documentary", label: "Documentary", description: "Observed reality and available light.", promptFragment: "Documentary presentation with observed behavior, available light, unforced framing, and the texture of a real place." },
  { id: "commercial", category: "Commercial / Brand Ad", label: "Commercial", description: "Polished product clarity and appetite.", promptFragment: "Commercial presentation with polished clarity, appetizing light, precise product emphasis, and a clean cinematic finish." },
];

export const SCENE_CATEGORIES = [...new Set(SCENE_PRESETS.map((item) => item.category))];
