import type { PromptPreset } from "./types";

export const SHOT_PRESETS: PromptPreset[] = [
  { id: "ews", category: "Framing", label: "Extreme Wide Shot", crop: 0.22, description: "The place dominates and the figure is small within it.", promptFragment: "Extreme wide establishing shot, emphasizing vast environmental scale and a small figure within the place." },
  { id: "ws", category: "Framing", label: "Wide Shot", crop: 0.34, description: "The full body and a generous amount of the location.", promptFragment: "Wide shot showing the full body and a generous amount of the surrounding location." },
  { id: "fs", category: "Framing", label: "Full Shot", crop: 0.46, description: "Head to toe, with the body as the subject.", promptFragment: "Full shot framing the body from head to toe, with the person as the subject and the place still readable." },
  { id: "cowboy", category: "Framing", label: "Cowboy Shot", crop: 0.52, description: "Mid-thigh up, a classic action frame.", promptFragment: "Cowboy shot framed from mid-thigh upward, with room for stance and gesture." },
  { id: "mws", category: "Framing", label: "Medium Wide Shot", crop: 0.58, description: "Knees or thighs up, balancing body and face.", promptFragment: "Medium wide shot balancing the body and the face, with the setting still present." },
  { id: "ms", category: "Framing", label: "Medium Shot", crop: 0.66, description: "Waist up, the everyday dialogue frame.", promptFragment: "Medium shot from the waist up, suited to dialogue and gesture." },
  { id: "mcu", category: "Framing", label: "Medium Close-Up", crop: 0.74, description: "Chest up, where performance reads clearly.", promptFragment: "Medium close-up from the chest upward, with clear facial performance and a simplified background." },
  { id: "cu", category: "Framing", label: "Close-Up", crop: 0.84, description: "The face fills the frame.", promptFragment: "Close-up on the face, with expression carrying the frame." },
  { id: "ecu", category: "Framing", label: "Extreme Close-Up", crop: 0.94, description: "Eyes, mouth, or a single telling detail.", promptFragment: "Extreme close-up on a single facial detail, with everything else falling away." },
  { id: "insert", category: "Framing", label: "Insert Shot", crop: 0.9, description: "An object the story needs the viewer to notice.", promptFragment: "Insert shot isolating a story object so the viewer can read it clearly." },
  { id: "detail", category: "Framing", label: "Detail Shot", crop: 0.96, description: "Texture, a hand, a mark, a small truth.", promptFragment: "Detail shot on texture or a small physical truth, held long enough to read." },
  { id: "eye-level", category: "Angle", label: "Eye Level", crop: 0.7, description: "A neutral, conversational height.", promptFragment: "Eye-level angle, neutral and conversational." },
  { id: "low", category: "Angle", label: "Low Angle", crop: 0.68, description: "The subject rises above the lens.", promptFragment: "Low angle looking up, giving the subject height and presence." },
  { id: "high", category: "Angle", label: "High Angle", crop: 0.68, description: "The lens looks down on the subject.", promptFragment: "High angle looking down, placing the subject under the viewer's gaze." },
  { id: "dutch", category: "Angle", label: "Dutch Angle", crop: 0.7, description: "The horizon tilts and the moment feels unstable.", promptFragment: "Dutch angle with a tilted horizon, making the moment feel unstable." },
  { id: "overhead", category: "Angle", label: "Overhead", crop: 0.4, description: "Straight down, a map of the action.", promptFragment: "Overhead angle looking straight down, reading the action like a map." },
  { id: "worms", category: "Angle", label: "Worm's-Eye View", crop: 0.62, description: "From the floor, the world looms.", promptFragment: "Worm's-eye view from the floor, with the world looming above the lens." },
  { id: "ots", category: "Relationship", label: "Over-the-Shoulder", crop: 0.72, description: "One figure frames the person they face.", promptFragment: "Over-the-shoulder shot, with one figure framing the person they face." },
  { id: "two", category: "Relationship", label: "Two Shot", crop: 0.5, description: "Two people share the frame.", promptFragment: "Two shot holding both people in the same frame and the same moment." },
  { id: "three", category: "Relationship", label: "Three Shot", crop: 0.42, description: "Three people, and the relationship among them.", promptFragment: "Three shot arranging three people so their relationship reads in one frame." },
  { id: "group", category: "Relationship", label: "Group Shot", crop: 0.32, description: "The ensemble occupies the place together.", promptFragment: "Group shot gathering the ensemble in one shared place." },
  { id: "profile", category: "Relationship", label: "Profile Shot", crop: 0.74, description: "The face in profile, graphic and quiet.", promptFragment: "Profile shot of the face, graphic and quiet." },
  { id: "pov", category: "Relationship", label: "POV", crop: 0.55, description: "We see what the character sees.", promptFragment: "Point-of-view shot showing what the character sees." },
  { id: "reverse-pov", category: "Relationship", label: "Reverse POV", crop: 0.72, description: "We look back at the person who is looking.", promptFragment: "Reverse point-of-view shot looking back at the person who is looking." },
  { id: "tracking", category: "Movement", label: "Tracking Shot", crop: 0.6, description: "The camera travels with the subject.", promptFragment: "Tracking shot traveling alongside the subject." },
  { id: "dolly-in", category: "Movement", label: "Dolly In", crop: 0.7, description: "A physical move closer, not a zoom.", promptFragment: "Dolly in, a physical move closer rather than a zoom." },
  { id: "dolly-out", category: "Movement", label: "Dolly Out", crop: 0.48, description: "A physical move away, revealing more of the place.", promptFragment: "Dolly out, a physical move away that reveals more of the place." },
  { id: "push", category: "Movement", label: "Push In", crop: 0.78, description: "A slow emphasis toward the subject.", promptFragment: "Slow push in toward the subject for emphasis." },
  { id: "pull", category: "Movement", label: "Pull Back", crop: 0.4, description: "The frame opens and context returns.", promptFragment: "Pull back as the frame opens and the context returns." },
  { id: "crane", category: "Movement", label: "Crane Shot", crop: 0.36, description: "The camera rises or descends through the space.", promptFragment: "Crane shot rising or descending through the space." },
  { id: "orbit", category: "Movement", label: "Orbit Shot", crop: 0.62, description: "The camera circles the subject.", promptFragment: "Orbit shot circling the subject." },
  { id: "arc", category: "Movement", label: "Arc Shot", crop: 0.58, description: "A partial circle that changes the angle.", promptFragment: "Arc shot moving partway around the subject to change the angle." },
  { id: "pedestal", category: "Movement", label: "Pedestal", crop: 0.66, description: "The camera rises or lowers in place.", promptFragment: "Pedestal move, the camera rising or lowering in place." },
  { id: "pan", category: "Movement", label: "Pan", crop: 0.5, description: "The camera turns left or right.", promptFragment: "Pan turning the camera across the scene." },
  { id: "tilt", category: "Movement", label: "Tilt", crop: 0.55, description: "The camera looks up or down.", promptFragment: "Tilt looking up or down through the scene." },
  { id: "handheld", category: "Movement", label: "Handheld", crop: 0.68, description: "A human, breathing camera.", promptFragment: "Handheld camera with a human, breathing presence." },
  { id: "steadicam", category: "Movement", label: "Steadicam", crop: 0.58, description: "Floating movement that stays smooth.", promptFragment: "Steadicam move, floating and smooth through the space." },
  { id: "locked", category: "Movement", label: "Locked-Off", crop: 0.64, description: "The camera does not move.", promptFragment: "Locked-off static frame, with the action happening inside a still camera." },
];

export const SHOT_CATEGORIES = [...new Set(SHOT_PRESETS.map((item) => item.category))];
