"""Environment Reference Sheet + Scene Creator shared contracts.

FROZEN CONTRACT — Law #16. Do not change field names without primary approval.
These are consumed by:
- Co-Director capability handlers (atlas_generate, ers_generate, scene_generate)
- Scene Creator REST router
- Entity resolver (@/# tag compilation)
- Agent Operation Overlay (surface types + child jobs)
- Library + Timeline integration

Amendment #2 (ERS COMPOSITION): the ERS sheet is assembled programmatically
in code from completed directional assets + authoritative structured data.
It is NOT generated by an image model. This prevents hallucinated text,
misspelled character names, and invented geometry.

Amendment #3 (SPATIAL AUTHORITY): Spatial Map coordinates are authoritative.
Generated directional images and Scene Creator images are visual
interpretations and may NEVER silently update placement state.

Amendment #4 (ORIENTATION): Atlas North = top edge of the approved Atlas
Shot. N/E/S/W are scene-relative directional views, not literal compass
headings.
"""

from __future__ import annotations

import uuid
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field


# Amendment #4 — scene-relative orientation. `atlas-north-up` means the top
# edge of the approved Atlas Shot is treated as "North". Not geographic.
ERSOrientation = Literal["atlas-north-up", "geographic-supplied"]

DirectionLabel = Literal["north", "east", "south", "west"]


class EnvironmentReferencePackage(BaseModel):
    """Structured backing for an Environment Reference Sheet.

    The visible ERS sheet is the presentation layer; this is the data layer.
    Stores references to Library assets only — no duplicate media blobs.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str
    scene_layout_id: str  # the SpatialMapDocument.id
    atlas_asset_id: Optional[str] = None
    master_environment_asset_id: Optional[str] = None
    # Snapshot of spatial map placements at generation time (authoritative,
    # per amendment #3). Generation may never mutate these.
    placements: list[dict] = Field(default_factory=list)
    style_context: dict = {}
    orientation: ERSOrientation = "atlas-north-up"
    # Real generated directional asset IDs (amendment #2: AI generates views).
    directional_assets: dict[DirectionLabel, Optional[str]] = {
        "north": None,
        "east": None,
        "south": None,
        "west": None,
    }
    # Programmatically assembled composite (amendment #2). NOT image-generated.
    ers_composite_asset_id: Optional[str] = None
    metadata: dict = {}
    created_at: str = ""
    updated_at: str = ""


class ShotRequest(BaseModel):
    """One parsed shot request from the Scene Creator textarea.

    Tags resolve to stable entity IDs; the textual tag is the friendly
    reference, not the database identity (amendment #5).
    """

    index: int
    raw_text: str
    characters: list[str] = Field(default_factory=list)  # resolved character_ids
    prop_entities: list[str] = Field(default_factory=list)  # resolved prop entity ids
    framing: str = ""
    angle: str = ""
    orientation: str = ""
    additional_instructions: str = ""


class SceneGenerationBatch(BaseModel):
    """A batch of generated scene images from one Scene Creator run."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str
    ers_package_id: str
    shot_requests: list[ShotRequest] = Field(default_factory=list)
    output_count: int = 4
    result_asset_ids: list[str] = Field(default_factory=list)
    collection_id: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""


class PropEntity(BaseModel):
    """A project-scoped prop backing a #prop tag.

    Identity:
    - ``id`` is canonical propId.
    - ``approved_asset_id`` is canonical visual identity.
    - ``library_asset_id`` may only *mirror* approved_asset_id after Use This Prop.
    - ``reference_asset_id`` is the creator-supplied source; removing it must not
      delete the approved identity.
    Drafts may omit approved_asset_id. Spatial Map production picker is approved-only.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str
    tag: str = ""  # normalized friendly reference, e.g. "coffee-cup"
    display_label: str = ""
    library_asset_id: str = ""  # mirror of approved_asset_id after approval; empty on draft
    notes: str = ""
    visual_style: str = ""
    description: str = ""
    reference_asset_id: Optional[str] = None
    approved_asset_id: Optional[str] = None
    candidates: list["PropCandidate"] = Field(default_factory=list)
    generator: "GeneratorSourceSelection" = Field(default_factory=lambda: GeneratorSourceSelection())
    created_at: str = ""
    updated_at: str = ""


# Character slot colors (V1). Amendment: accessible labels in addition to color.
CHARACTER_SLOT_COLORS: tuple[str, ...] = ("red", "blue", "orange", "green")
PROP_SLOT_COLORS: tuple[str, ...] = ("purple", "brown", "aqua", "gray")

CHARACTER_SLOT_LABELS: tuple[str, ...] = (
    "Character 1 (Red)",
    "Character 2 (Blue)",
    "Character 3 (Orange)",
    "Character 4 (Green)",
)
PROP_SLOT_LABELS: tuple[str, ...] = (
    "Prop 1 (Purple)",
    "Prop 2 (Brown)",
    "Prop 3 (Aqua)",
    "Prop 4 (Gray)",
)


# ---------------------------------------------------------------------------
# Scene Creator Express / Standard — Scene ≠ Shot ≠ Candidate (frozen)
# Creator-facing ERS identity is sheetId. Package UUIDs stay internal.
# ---------------------------------------------------------------------------

CinematicShotSize = Literal[
    "wide",
    "medium_wide",
    "medium",
    "close_up",
    "extreme_close_up",
]
CinematicMotion = Literal["static", "pan", "tilt", "dolly", "handheld"]
CinematicFraming = Literal["single", "two_shot", "group", "over_shoulder", "pov"]
CandidateSource = Literal["local", "api"]
CandidateStatus = Literal["queued", "generating", "complete", "failed"]


class CinematicShotControls(BaseModel):
    """HOW the shot is interpreted. Never written back to Spatial Map."""

    shot_size: str = "medium_wide"
    motion: str = "static"
    framing: str = "two_shot"


class SceneCreatorCamera(BaseModel):
    """WHERE from Spatial Map + HOW from Scene Creator.

    Spatial fields (slot, orientation, FOV) are snapshots. Cinematic overrides
    stay on the shot and are never silently written back to Spatial Map.
    """

    camera_id: str = ""
    camera_slot: Optional[int] = None  # 0-3 display as C1-C4; None = Default Camera
    label: str = "Default Camera"
    orientation: str = ""
    fov_preset: str = ""
    yaw_degrees: Optional[float] = None
    lens_mm: Optional[float] = None
    cinematic: CinematicShotControls = Field(default_factory=CinematicShotControls)


class GeneratorSourceSelection(BaseModel):
    """User Control Law: an unchecked source produces zero jobs to that source."""

    local_enabled: bool = True
    api_enabled: bool = False
    local_family: str = ""
    api_provider: str = ""
    api_model: str = ""
    local_models: list[dict[str, Any]] = Field(default_factory=list)
    api_models: list[dict[str, Any]] = Field(default_factory=list)
    style_engine_enabled: bool = False
    style_engine_model_id: str = ""
    generator_sources: Optional[dict[str, Any]] = None


class SceneShotTakeMemory(BaseModel):
    """Adept UI Take Law — same product law as Timeline Re-Take.

    User correction is a DELTA. Take A remains authoritative until Take B
    is approved. Do not collapse into one opaque prompt.
    """

    originalTakeIntent: dict = Field(default_factory=dict)
    sceneErsState: dict = Field(default_factory=dict)
    characterIdentity: dict = Field(default_factory=dict)
    blocking: dict = Field(default_factory=dict)
    camera: dict = Field(default_factory=dict)
    takeState: dict = Field(default_factory=dict)
    userCorrection: dict = Field(default_factory=dict)


class SceneShotCandidate(BaseModel):
    """One generated visual take of a Shot. Never a Shot itself."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    shot_id: str = ""
    index: int = 0
    job_id: str = ""
    asset_id: Optional[str] = None
    status: CandidateStatus = "queued"
    source: CandidateSource = "local"
    family: str = ""
    model: str = ""
    seed: Optional[int] = None
    provenance_label: str = ""
    take_label: str = ""
    error: str = ""
    created_at: str = ""
    camera_state_version: Optional[int] = None
    camera_state_hash: str = ""
    source_camera_id: str = ""
    quality_profile: str = ""
    kind: str = ""
    parent_candidate_id: Optional[str] = None
    mask_id: Optional[str] = None
    edit_operation: Optional[str] = None
    final_strategy: str = ""
    source_preview_asset_id: Optional[str] = None
    approved_edited_preview_asset_id: Optional[str] = None
    final_model_id: str = ""
    final_workflow_key: str = ""
    region_edit_ids: list[str] = Field(default_factory=list)
    mask_asset_ids: list[str] = Field(default_factory=list)
    error_detail: str = ""
    superseded: bool = False


class PropCandidate(BaseModel):
    """One generated identity look of a project Prop. Never a Prop itself."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    prop_id: str = ""
    index: int = 0
    job_id: str = ""
    asset_id: Optional[str] = None
    status: CandidateStatus = "queued"
    source: CandidateSource = "local"
    family: str = ""
    model: str = ""
    seed: Optional[int] = None
    provenance_label: str = ""
    conditioning: Literal["reference_conditioned", "description_guided"] = "description_guided"
    take_label: str = ""
    error: str = ""
    created_at: str = ""


class SceneShot(BaseModel):
    """One shot inside a Studio Scene. Owns intent, ERS, blocking, camera, prompt, candidates."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str
    scene_id: str  # required Studio Scene row — never empty
    sheet_id: str  # canonical creator-facing ERS identity
    ers_package_id: str = ""  # resolved internally; UI must not require this
    ers_runtime: bool = False  # True when package was constructed without regen
    intent: str = ""
    prompt: str = ""
    character_ids: list[str] = Field(default_factory=list)
    prop_entity_ids: list[str] = Field(default_factory=list)
    camera: SceneCreatorCamera = Field(default_factory=SceneCreatorCamera)
    generator: GeneratorSourceSelection = Field(default_factory=GeneratorSourceSelection)
    candidates: list[SceneShotCandidate] = Field(default_factory=list)
    approved_candidate_id: Optional[str] = None
    take_memory: SceneShotTakeMemory = Field(default_factory=SceneShotTakeMemory)
    generation_batch_id: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""


def normalize_prop_tag(label: str) -> str:
    """Normalize a human prop label into a project-safe tag.

    Examples:
        "Coffee Cup"       -> "coffee-cup"
        "Espresso Machine" -> "espresso-machine"
        "cup2"             -> "cup2"
        "Barista Bar"      -> "barista-bar"
    """
    import re

    s = label.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s)
    s = s.strip("-")
    return s or "prop"


PropEntity.model_rebuild()
