"""Environment Reference Sheet + Scene Creator shared contracts.

FROZEN CONTRACT — Law #16. Do not change field names without primary approval.
These are consumed by:
- Co-Director capability handlers (atlas_generate, ers_generate, scene_generate)
- Scene Creator REST router
- Entity resolver (@/# tag compilation)
- Agent Operation Overlay (surface types + child jobs)
- Library + Timeline integration

Amendment #2 (ERS COMPOSITION): the ERS sheet is assembled programmatically
in code from completed directional assets + authoritative structured data.
It is NOT generated by an image model. This prevents hallucinated text,
misspelled character names, and invented geometry.

Amendment #3 (SPATIAL AUTHORITY): Spatial Map coordinates are authoritative.
Generated directional images and Scene Creator images are visual
interpretations and may NEVER silently update placement state.

Amendment #4 (ORIENTATION): Atlas North = top edge of the approved Atlas
Shot. N/E/S/W are scene-relative directional views, not literal compass
headings.
"""

from __future__ import annotations

import uuid
from typing import Literal, Optional

from pydantic import BaseModel, Field


# Amendment #4 — scene-relative orientation. `atlas-north-up` means the top
# edge of the approved Atlas Shot is treated as "North". Not geographic.
ERSOrientation = Literal["atlas-north-up", "geographic-supplied"]

DirectionLabel = Literal["north", "east", "south", "west"]


class EnvironmentReferencePackage(BaseModel):
    """Structured backing for an Environment Reference Sheet.

    The visible ERS sheet is the presentation layer; this is the data layer.
    Stores references to Library assets only — no duplicate media blobs.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str
    scene_layout_id: str  # the SpatialMapDocument.id
    atlas_asset_id: Optional[str] = None
    master_environment_asset_id: Optional[str] = None
    # Snapshot of spatial map placements at generation time (authoritative,
    # per amendment #3). Generation may never mutate these.
    placements: list[dict] = Field(default_factory=list)
    style_context: dict = {}
    orientation: ERSOrientation = "atlas-north-up"
    # Real generated directional asset IDs (amendment #2: AI generates views).
    directional_assets: dict[DirectionLabel, Optional[str]] = {
        "north": None,
        "east": None,
        "south": None,
        "west": None,
    }
    # Programmatically assembled composite (amendment #2). NOT image-generated.
    ers_composite_asset_id: Optional[str] = None
    metadata: dict = {}
    created_at: str = ""
    updated_at: str = ""


class ShotRequest(BaseModel):
    """One parsed shot request from the Scene Creator textarea.

    Tags resolve to stable entity IDs; the textual tag is the friendly
    reference, not the database identity (amendment #5).
    """

    index: int
    raw_text: str
    characters: list[str] = Field(default_factory=list)  # resolved character_ids
    prop_entities: list[str] = Field(default_factory=list)  # resolved prop entity ids
    framing: str = ""
    angle: str = ""
    orientation: str = ""
    additional_instructions: str = ""


class SceneGenerationBatch(BaseModel):
    """A batch of generated scene images from one Scene Creator run."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str
    ers_package_id: str
    shot_requests: list[ShotRequest] = Field(default_factory=list)
    output_count: int = 4
    result_asset_ids: list[str] = Field(default_factory=list)
    collection_id: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""


class PropEntity(BaseModel):
    """A project-scoped prop/reference object backing a #prop tag.

    The Library image asset anchors visual identity (spec §17, §57).
    The tag is the normalized project-safe friendly reference
    (e.g. "Coffee Cup" -> "coffee-cup"). Amendment #5.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str
    tag: str  # normalized: lowercase, hyphenated, e.g. "coffee-cup"
    display_label: str  # human-friendly, e.g. "Coffee Cup"
    library_asset_id: str  # mandatory — anchors visual identity
    notes: str = ""
    created_at: str = ""
    updated_at: str = ""


# Character slot colors (V1). Amendment: accessible labels in addition to color.
CHARACTER_SLOT_COLORS: tuple[str, ...] = ("red", "blue", "orange", "green")
PROP_SLOT_COLORS: tuple[str, ...] = ("purple", "brown", "aqua", "gray")

CHARACTER_SLOT_LABELS: tuple[str, ...] = (
    "Character 1 (Red)",
    "Character 2 (Blue)",
    "Character 3 (Orange)",
    "Character 4 (Green)",
)
PROP_SLOT_LABELS: tuple[str, ...] = (
    "Prop 1 (Purple)",
    "Prop 2 (Brown)",
    "Prop 3 (Aqua)",
    "Prop 4 (Gray)",
)


def normalize_prop_tag(label: str) -> str:
    """Normalize a human prop label into a project-safe tag.

    Examples:
        "Coffee Cup"       -> "coffee-cup"
        "Espresso Machine" -> "espresso-machine"
        "cup2"             -> "cup2"
        "Barista Bar"      -> "barista-bar"
    """
    import re

    s = label.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s)
    s = s.strip("-")
    return s or "prop"
