"""Scene Creator Mini candidate validation — lightweight continuity gate.

Not an aesthetic judge. Verifies production requirements against the
CameraShotPacket facts: environment recognizable, required character present
and plausibly the right identity, character in the correct broad mapped
region, camera geography plausible, shot size broadly correct, major
architecture not mirrored.

Reuses the shared vision review layer (codirector.vision.vision_review) — no
new VLM infrastructure. Honest degrade: when no vision provider is
configured the candidate is VALIDATION_UNAVAILABLE (viewable, not selectable,
not Library-ingestable) — never a fake pass.
"""

from __future__ import annotations

import asyncio
import json
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..config import settings

VALIDATION_STATES = (
    "generating",
    "validating",
    "pass",
    "continuity_failed",
    "generation_failed",
    "validation_unavailable",
)

_INFLIGHT_TTL_SECONDS = 600

_GATE_INSTRUCTIONS = """You are a strict production-continuity reviewer for a scene still generated by Scene Creator Mini.

You are given:
1. PRODUCTION FACTS — the authoritative shot packet compiled from the saved Spatial Map (locked production truth).
2. THE CANDIDATE IMAGE — one generated still.

Verify ONLY production requirements. This is not an aesthetic judge: do not criticize lighting, style, or beauty. Creative interpretation of expression and lighting is allowed; production truth is not.

Check each field and respond with EXACTLY this format (one block per field):

FIELD: environment
PASS/FAIL: PASS or FAIL
FIELD: required_character_present
PASS/FAIL: PASS or FAIL
FIELD: subject_identity
PASS/FAIL: PASS or FAIL
FIELD: character_placement
PASS/FAIL: PASS or FAIL
FIELD: camera_geography
PASS/FAIL: PASS or FAIL
FIELD: shot_size
PASS/FAIL: PASS or FAIL
FIELD: no_mirror
PASS/FAIL: PASS or FAIL
VERDICT: PASS or FAIL
REASON: <one sentence, plain language>

Rules:
- required_character_present: FAIL when the production facts name a required character (MUST BE PRESENT) and that character is absent or replaced by another employee/person. When the facts require no character, mark PASS.
- subject_identity: FAIL unless the visible person's appearance (species, build, hair, ears, wardrobe) is CONSISTENT with the CHARACTER IDENTITY facts in PRODUCTION FACTS (e.g. pointed elf ears, high twin ponytails, dark layered clothing). A generic person who does not match the described appearance is a FAIL — the required character must be visually recognizable as that character.
- character_placement: FAIL when the required character stands in the wrong broad region (e.g. on the customer side instead of behind the counter) or the shot contradicts the placement lock lines.
- camera_geography: FAIL when the viewpoint contradicts the camera's cell/region/facing (e.g. a centered north-facing hero view from an east-facing camera), the room is mirrored, or another camera's viewpoint was substituted.
- shot_size: FAIL only when the framing is dramatically wrong for the stated shot size (e.g. a close-up instead of a wide). AUTO shot size always PASS.
- no_mirror: FAIL when the layout is mirrored or an invented room/layout appears.
- VERDICT is PASS only when every applicable field passes; any FAIL makes VERDICT FAIL."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _take_path(project_id: str, take_id: str) -> Path:
    return Path(settings.data_dir) / "projects" / project_id / "scene_creator_mini" / f"{take_id}.json"


def _load_take(project_id: str, take_id: str) -> dict[str, Any] | None:
    path = _take_path(project_id, take_id)
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _save_take(project_id: str, take_id: str, take: dict[str, Any]) -> None:
    path = _take_path(project_id, take_id)
    path.write_text(json.dumps(take, indent=2), encoding="utf-8")


def _fact_card(packet: dict[str, Any] | None, result: dict[str, Any]) -> str:
    if not packet:
        return (
            "No shot packet was recorded for this candidate. "
            "Verify only that the image is a single photographic still of a coherent environment."
        )
    lines: list[str] = []
    camera = packet.get("camera") or {}
    lines.append(f"CAMERA {camera.get('label') or '?'}: cell {camera.get('cell') or 'unknown'}, "
                 f"region {camera.get('region') or 'unknown'}, facing {camera.get('facing') or '?'}, "
                 f"FOV {camera.get('fovPreset') or '?'}, shot size {camera.get('shotSize') or 'auto'}.")
    env = packet.get("environment") or {}
    lines.append(f"ENVIRONMENT: {env.get('environmentIdentity') or 'unknown'} (map {env.get('spatialMapId') or '?'}, "
                 f"version {env.get('savedVersion') or env.get('mapVersion') or '?'}).")
    required = [c for c in packet.get("characters") or [] if c.get("mandatoryForCamera")]
    if required:
        for c in required:
            lines.append(
                f"REQUIRED CHARACTER: {c.get('name') or c.get('characterId')} MUST BE PRESENT, "
                f"placed at {c.get('cell') or 'unknown'}, region {c.get('region') or 'unknown'}."
            )
            identity_text = "; ".join(str(f) for f in (c.get("identityFacts") or []) if f).strip()
            if identity_text:
                lines.append(
                    f"CHARACTER IDENTITY ({c.get('name') or c.get('characterId')}): {identity_text}"
                )
            for side in c.get("sideRelations") or []:
                lines.append(f"PLACEMENT LOCK: {side}")
    else:
        lines.append("REQUIRED CHARACTER: none — no character presence is mandatory for this camera.")
    return "\n".join(lines)


def _asset_path(db: Any, asset_id: str) -> str:
    try:
        from ..db import Asset

        asset = db.get(Asset, asset_id)
        if asset is not None:
            return str(asset.path or "")
    except Exception:
        pass
    return ""


async def run_candidate_validation(db: Any, project_id: str, take_id: str, result_id: str) -> dict[str, Any] | None:
    """Validate one completed candidate and stamp the verdict onto the take.

    Idempotent: skips when a verdict already exists. Returns the new
    validation record, or None when nothing to do.
    """
    take = _load_take(project_id, take_id)
    if take is None:
        return None
    result = next((r for r in take.get("results") or [] if str(r.get("id") or "") == result_id), None)
    if result is None:
        return None
    asset_id = str(result.get("assetId") or "").strip()
    image_path = _asset_path(db, asset_id) if asset_id else ""
    return await _run_with_asset_path(project_id, take_id, result_id, asset_path=image_path)


async def _run_with_asset_path(
    project_id: str,
    take_id: str,
    result_id: str,
    asset_path: str,
) -> dict[str, Any] | None:
    """Shared validation runner. asset_path may be empty (unresolvable)."""
    take = _load_take(project_id, take_id)
    if take is None:
        return None
    result = next((r for r in take.get("results") or [] if str(r.get("id") or "") == result_id), None)
    if result is None:
        return None
    existing = result.get("validation")
    if isinstance(existing, dict) and existing.get("verdict"):
        return existing
    # pendingSince = an actual validation call is in flight (set by the
    # runner right before the VLM call). scheduledAt alone (set by the
    # hydrate scheduler) must NOT block the runner it spawned.
    if isinstance(existing, dict) and existing.get("pendingSince"):
        try:
            started = datetime.fromisoformat(str(existing["pendingSince"]))
            age = (datetime.now(timezone.utc) - started).total_seconds()
        except Exception:
            age = 0.0
        if age < _INFLIGHT_TTL_SECONDS:
            return existing

    result["validation"] = {"state": "validating", "pendingSince": _now()}
    _save_take(project_id, take_id, take)

    image_path = str(asset_path or "")
    packet = (take.get("cameraPackets") or {}).get(str(result.get("cameraId") or "")) or {}
    fact_card = _fact_card(packet, result)

    from ..codirector.vision.vision_review import chat_vision, chat_vision_fal, parse_field_verdicts

    if not image_path or not Path(image_path).is_file():
        record = {
            "state": "validation_unavailable",
            "verdict": "NOT_VERIFIED",
            "summary": "Candidate image file is missing; validation could not run.",
            "model": "",
            "checkedAt": _now(),
        }
        result["validation"] = record
        _save_take(project_id, take_id, take)
        return record

    prompt = _GATE_INSTRUCTIONS + "\n\nPRODUCTION FACTS:\n" + fact_card + "\n\nCANDIDATE IMAGE (under review):"

    # Provider priority: fal any-llm/vision (public URL) -> Kie Gemini (data URL).
    # fal requires a public URL; the Cloudflare public base is configured in
    # production so candidate assets are reachable.
    from ..codirector.vision.vision_review import data_url_from_path
    from ..config import settings as _settings

    asset_id = str(result.get("assetId") or "").strip()
    public_base = str(getattr(_settings, "public_api_base_url", "") or "").rstrip("/")
    public_url = f"{public_base}/api/assets/{asset_id}/file" if public_base and asset_id else ""
    response: dict[str, Any] | None = None
    if public_url:
        response = await chat_vision_fal(prompt=prompt, image_urls=[public_url])
    if response is None or not response.get("ok"):
        image_url = data_url_from_path(image_path)
        if image_url:
            response = await chat_vision(
                instructions=_GATE_INSTRUCTIONS,
                parts=[
                    {"type": "text", "text": "PRODUCTION FACTS:\n" + fact_card},
                    {"type": "text", "text": "CANDIDATE IMAGE (under review):"},
                    {"type": "image_url", "image_url": {"url": image_url}},
                ],
                temperature=0.0,
            )
    if response is None:
        record = {
            "state": "validation_unavailable",
            "verdict": "NOT_VERIFIED",
            "summary": "Candidate image could not be read; validation could not run.",
            "model": "",
            "checkedAt": _now(),
        }
        result["validation"] = record
        _save_take(project_id, take_id, take)
        return record
    if not response.get("ok"):
        reason = str(response.get("reason") or response.get("error") or "vlm_error")
        if reason == "no_vlm_configured":
            record = {
                "state": "validation_unavailable",
                "verdict": "NOT_VERIFIED",
                "summary": "Continuity review could not run — no vision-capable provider is configured.",
                "model": "",
                "checkedAt": _now(),
                "reason": reason,
            }
        else:
            # Transient error: clear the in-flight marker so a later poll retries.
            record = {
                "state": "validating",
                "verdict": "",
                "summary": "Continuity review provider error; will retry.",
                "model": "",
                "checkedAt": _now(),
                "reason": reason,
            }
        result["validation"] = record
        _save_take(project_id, take_id, take)
        return record

    fields = parse_field_verdicts(str(response.get("output") or ""))
    overall = str(fields.get("VERDICT") or "FAIL")
    reason = ""
    for line in str(response.get("output") or "").splitlines():
        if line.strip().lower().startswith("reason:"):
            reason = line.split(":", 1)[1].strip()[:300]
            break
    record = {
        "state": "pass" if overall == "PASS" else "continuity_failed",
        "verdict": overall,
        "fields": fields,
        "summary": reason or ("Passed continuity review." if overall == "PASS" else "Failed continuity review."),
        "model": str(response.get("model") or "gemini-3-pro"),
        "provider": str(response.get("provider") or "kie"),
        "checkedAt": _now(),
    }
    result["validation"] = record
    _save_take(project_id, take_id, take)
    return record


async def run_candidate_validation_for_job(
    *,
    project_id: str,
    take_id: str,
    job_id: str,
    asset_path: str,
) -> dict[str, Any] | None:
    """Worker hook: validate the take result whose job just completed."""
    take = _load_take(project_id, take_id)
    if take is None:
        return None
    result = next(
        (r for r in take.get("results") or [] if str(r.get("jobId") or "") == str(job_id)),
        None,
    )
    if result is None:
        return None
    result_id = str(result.get("id") or "")
    if not result_id:
        return None
    if not result.get("assetId"):
        result["assetId"] = _asset_id_for_job(project_id, take_id, job_id)
        if not result.get("assetId"):
            return None
        _save_take(project_id, take_id, take)
    # Force the asset path so no DB session is needed in the worker task.
    return await _run_with_asset_path(
        project_id, take_id, result_id, asset_path=asset_path
    )


def _asset_id_for_job(project_id: str, take_id: str, job_id: str) -> str:
    take = _load_take(project_id, take_id)
    if take is None:
        return ""
    result = next((r for r in take.get("results") or [] if str(r.get("jobId") or "") == str(job_id)), None)
    return str((result or {}).get("assetId") or "")


def run_candidate_validation_sync(db: Any, project_id: str, take_id: str, result_id: str) -> dict[str, Any] | None:
    """Sync wrapper (thread-safe fallback for hydrate paths)."""
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None
    if loop is not None:
        raise RuntimeError("run_candidate_validation_sync must not run inside an event loop")
    return asyncio.run(run_candidate_validation(db, project_id, take_id, result_id))


def schedule_validation(project_id: str, take_id: str, result_id: str) -> None:
    """Fire-and-forget validation in a daemon thread (hydrate fallback).

    Uses a FRESH DB session inside the thread — the request-bound session is
    not thread-safe and must never cross threads.
    """

    def _work() -> None:
        try:
            from ..db import SessionLocal

            with SessionLocal() as db:
                run_candidate_validation_sync(db, project_id, take_id, result_id)
        except Exception:
            pass

    threading.Thread(target=_work, daemon=True, name=f"mini-validate-{result_id[:8]}").start()


def validation_state_for_result(result: dict[str, Any]) -> str:
    """Map a Mini result row to the product validation state."""
    status = str(result.get("status") or "").lower()
    if status in {"failed", "error", "cancelled", "canceled"}:
        return "generation_failed"
    if status in {"queued"}:
        return "generating"
    if status not in {"complete", "completed", "success", "done"}:
        return "generating"
    validation = result.get("validation")
    if not isinstance(validation, dict):
        return "validating"
    state = str(validation.get("state") or "")
    if state in {"pass", "continuity_failed", "validation_unavailable"}:
        return state
    return "validating"


def result_is_selectable(result: dict[str, Any]) -> bool:
    """Only PASS-validated, completed, non-library candidates are selectable."""
    if result.get("inLibrary"):
        return False
    if validation_state_for_result(result) != "pass":
        return False
    return bool(result.get("assetId"))
