"""Canonical product ports and lifecycle bounds."""

from __future__ import annotations

API_PORT = 8758
COMFY_PORT = 8188
OLLAMA_PORT = 11434
RETIRED_WEB_PORT = 8760
DEV_API_PORT = 8742
H3_COMFY_PORT = 8192
VITE_PORT = 5173

API_HOST = "127.0.0.1"

SERVICES = ("studio_api", "comfyui", "cloudflared", "ollama")

MAX_RESTARTS = 5
STORM_WINDOW_SEC = 300
BASE_BACKOFF_SEC = 5
MAX_BACKOFF_SEC = 120
BUSY_ALIVE_CYCLES = 20

API_READY_TIMEOUT_SEC = 120
COMFY_READY_TIMEOUT_SEC = 45
TUNNEL_READY_TIMEOUT_SEC = 20
OLLAMA_READY_TIMEOUT_SEC = 15
PORT_RELEASE_TIMEOUT_SEC = 15

API_HEALTH_PATH = "/api/healthz"
COMFY_STATS_PATH = "/system_stats"
COMFY_QUEUE_PATH = "/queue"
OLLAMA_TAGS_PATH = "/api/tags"

TUNNEL_NAME = "adept-ui-beta"
TUNNEL_HOSTNAME = "api-beta.adeptui.org"
