"""Reason codes for Co-Director DeliberationDecision (cd-deliberation-v1).

Machine-readable codes only — never chain-of-thought. Prefer these enums over
free-form prose in reasonCodes.
"""

from __future__ import annotations

# --- Positive / grounded ---
PROJECT_GROUNDED = "PROJECT_GROUNDED"
SCENE_GROUNDED = "SCENE_GROUNDED"
ENTITY_RESOLVED = "ENTITY_RESOLVED"
REFERENCE_RESOLVED = "REFERENCE_RESOLVED"
CANONICAL_REQUEST_FOUND = "CANONICAL_REQUEST_FOUND"
DEFAULTS_SUFFICIENT = "DEFAULTS_SUFFICIENT"
EXPLICIT_MODEL_OVERRIDE = "EXPLICIT_MODEL_OVERRIDE"
RUNTIME_READY = "RUNTIME_READY"
ACT_READY = "ACT_READY"
COMMITMENT_EXPLICIT = "COMMITMENT_EXPLICIT"
COMMITMENT_IMPLIED = "COMMITMENT_IMPLIED"
SUFFICIENCY_OK = "SUFFICIENCY_OK"
CAPABILITY_SELECTED = "CAPABILITY_SELECTED"
PRODUCTION_MEMORY_PREFERRED = "PRODUCTION_MEMORY_PREFERRED"
REFERENTIAL_MATCHED = "REFERENTIAL_MATCHED"
GROUNDING_TALK = "GROUNDING_TALK"
CLASSIFIER_EVIDENCE = "CLASSIFIER_EVIDENCE"

# --- Blocking / ask / stop ---
TARGET_AMBIGUOUS = "TARGET_AMBIGUOUS"
STRICT_MODEL_UNAVAILABLE = "STRICT_MODEL_UNAVAILABLE"
MISSING_REQUIRED_REFERENCE = "MISSING_REQUIRED_REFERENCE"
RUNTIME_UNAVAILABLE = "RUNTIME_UNAVAILABLE"
DESTRUCTIVE_CONFIRMATION_REQUIRED = "DESTRUCTIVE_CONFIRMATION_REQUIRED"
CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
ENTITY_UNRESOLVED = "ENTITY_UNRESOLVED"
PROJECT_UNBOUND = "PROJECT_UNBOUND"
SCENE_REQUIRED = "SCENE_REQUIRED"
CAPABILITY_UNCLEAR = "CAPABILITY_UNCLEAR"
COMMITMENT_WITHOUT_TARGET = "COMMITMENT_WITHOUT_TARGET"
INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"
RISK_CONFIRMATION_REQUIRED = "RISK_CONFIRMATION_REQUIRED"
CONTRADICTORY_CONSTRAINTS = "CONTRADICTORY_CONSTRAINTS"
CHAT_INHERIT_FALLBACK = "CHAT_INHERIT_FALLBACK"
FAILURE_INFORMED_RETRY = "FAILURE_INFORMED_RETRY"
SCENE_UNBOUND_ASK = "SCENE_UNBOUND_ASK"
ENTITY_INFLUENCED_PLAN = "ENTITY_INFLUENCED_PLAN"
DEEP_EFFORT = "DEEP_EFFORT"
FAST_EFFORT = "FAST_EFFORT"
DIALOGUE_PLAN_SUBORDINATE = "DIALOGUE_PLAN_SUBORDINATE"
PENDING_CONFIRM_PATH = "PENDING_CONFIRM_PATH"
POST_ACTION_RECONCILED = "POST_ACTION_RECONCILED"
COMPETING_AUTHORITY_BLOCKED = "COMPETING_AUTHORITY_BLOCKED"
DEFERRED_INTENT = "DEFERRED_INTENT"
QUOTED_COMMAND_PROTECTED = "QUOTED_COMMAND_PROTECTED"
DESTRUCTIVE_DISCUSSION = "DESTRUCTIVE_DISCUSSION"
PROVIDER_ROUTE_COMMAND = "PROVIDER_ROUTE_COMMAND"
REFERENTIAL_ENHANCE = "REFERENTIAL_ENHANCE"
HYPOTHETICAL_QUERY = "HYPOTHETICAL_QUERY"
FUTURE_INTENT = "FUTURE_INTENT"
NO_ENQUEUE_REQUEST = "NO_ENQUEUE_REQUEST"
UNKNOWN_CAST_SUBJECT = "UNKNOWN_CAST_SUBJECT"
STRICT_TARGET_REQUIRED = "STRICT_TARGET_REQUIRED"


# --- Production Planner ---
PRODUCTION_PLAN_ATTACHED = "PRODUCTION_PLAN_ATTACHED"
PLANNING_SPEECH = "PLANNING_SPEECH"
MULTI_STEP_COMPILED = "MULTI_STEP_COMPILED"
PENDING_BRIEF_READY = "PENDING_BRIEF_READY"
PENDING_BRIEF_BOUND = "PENDING_BRIEF_BOUND"
PENDING_BRIEF_EXPIRED = "PENDING_BRIEF_EXPIRED"
PENDING_BRIEF_MISSING = "PENDING_BRIEF_MISSING"
DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
SELECTIVE_PREFLIGHT = "SELECTIVE_PREFLIGHT"
INTENT_EVIDENCE_BUILT = "INTENT_EVIDENCE_BUILT"

ALL_REASON_CODES: frozenset[str] = frozenset(
    {
        PROJECT_GROUNDED,
        SCENE_GROUNDED,
        ENTITY_RESOLVED,
        REFERENCE_RESOLVED,
        CANONICAL_REQUEST_FOUND,
        DEFAULTS_SUFFICIENT,
        EXPLICIT_MODEL_OVERRIDE,
        RUNTIME_READY,
        ACT_READY,
        COMMITMENT_EXPLICIT,
        COMMITMENT_IMPLIED,
        SUFFICIENCY_OK,
        CAPABILITY_SELECTED,
        PRODUCTION_MEMORY_PREFERRED,
        REFERENTIAL_MATCHED,
        GROUNDING_TALK,
        CLASSIFIER_EVIDENCE,
        TARGET_AMBIGUOUS,
        STRICT_MODEL_UNAVAILABLE,
        MISSING_REQUIRED_REFERENCE,
        RUNTIME_UNAVAILABLE,
        DESTRUCTIVE_CONFIRMATION_REQUIRED,
        CLARIFICATION_REQUIRED,
        ENTITY_UNRESOLVED,
        PROJECT_UNBOUND,
        SCENE_REQUIRED,
        CAPABILITY_UNCLEAR,
        COMMITMENT_WITHOUT_TARGET,
        INSUFFICIENT_CONTEXT,
        RISK_CONFIRMATION_REQUIRED,
        CONTRADICTORY_CONSTRAINTS,
        CHAT_INHERIT_FALLBACK,
        FAILURE_INFORMED_RETRY,
        SCENE_UNBOUND_ASK,
        ENTITY_INFLUENCED_PLAN,
        DEEP_EFFORT,
        FAST_EFFORT,
        DIALOGUE_PLAN_SUBORDINATE,
        PENDING_CONFIRM_PATH,
        POST_ACTION_RECONCILED,
        COMPETING_AUTHORITY_BLOCKED,
        DEFERRED_INTENT,
        QUOTED_COMMAND_PROTECTED,
        DESTRUCTIVE_DISCUSSION,
        PROVIDER_ROUTE_COMMAND,
        REFERENTIAL_ENHANCE,
        HYPOTHETICAL_QUERY,
        FUTURE_INTENT,
        NO_ENQUEUE_REQUEST,
        UNKNOWN_CAST_SUBJECT,
        STRICT_TARGET_REQUIRED,
        PRODUCTION_PLAN_ATTACHED,
        PLANNING_SPEECH,
        MULTI_STEP_COMPILED,
        PENDING_BRIEF_READY,
        PENDING_BRIEF_BOUND,
        PENDING_BRIEF_EXPIRED,
        PENDING_BRIEF_MISSING,
        DEPENDENCY_BLOCKED,
        SELECTIVE_PREFLIGHT,
        INTENT_EVIDENCE_BUILT,
    }
)
