"""Server-side view of the canonical PoseCraft pose catalog.

The catalog's single source of truth is the TypeScript module
``studio-web/src/posecraft/poseCatalog.ts``. The JSON mirror next to this
file (``pose_catalog.json``) is generated by
``studio-web/scripts/export-pose-catalog.ts`` and a vitest contract test
(``poseCatalogExport.test.ts``) fails the web build if the mirror drifts.

Used by the Co-Director ``posecraft.apply_pose`` handler to resolve a pose
preset id into real joint rotations so an approved pose command changes the
actual persisted scene (not just an acknowledgement).
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from .schemas import JOINT_NAMES

_CATALOG_PATH = Path(__file__).with_name("pose_catalog.json")


@lru_cache(maxsize=1)
def _load_catalog() -> dict[str, Any]:
    with _CATALOG_PATH.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if data.get("schema") != "posecraft-pose-catalog@1":
        raise ValueError(f"Unexpected pose catalog schema: {data.get('schema')!r}")
    return data


@lru_cache(maxsize=1)
def _poses_by_id() -> dict[str, dict[str, Any]]:
    return {p["id"]: p for p in _load_catalog()["poses"]}


def joint_limits() -> dict[str, dict[str, list[float]]]:
    return _load_catalog()["jointLimits"]


def get_catalog_pose(pose_id: str) -> dict[str, Any] | None:
    """Return {id, label, category, description, archetypes, joints} or None."""
    return _poses_by_id().get(pose_id)


def clamp_rotation(joint: str, axis: str, value: float) -> float:
    limits = joint_limits().get(joint)
    if not limits or axis not in limits:
        return float(value)
    lo, hi = limits[axis]
    return float(min(max(value, lo), hi))


def clamped_pose_map(joints: dict[str, Any]) -> dict[str, dict[str, float]]:
    """Full 17-joint pose map (missing joints zeroed), clamped to limits."""
    pose: dict[str, dict[str, float]] = {}
    for joint in JOINT_NAMES:
        rot = joints.get(joint) or {}
        pose[joint] = {
            "x": clamp_rotation(joint, "x", float(rot.get("x", 0.0))),
            "y": clamp_rotation(joint, "y", float(rot.get("y", 0.0))),
            "z": clamp_rotation(joint, "z", float(rot.get("z", 0.0))),
        }
    return pose


def is_pose_compatible(pose: dict[str, Any], archetype_id: str) -> bool:
    archetypes = pose.get("archetypes")
    if not archetypes:
        return True
    return archetype_id in archetypes
