"""Adept-owned extra_model_paths.yaml. Never launch with Desktop YAML.

Model roots come from canonical runtime.json. Tests may still patch
QWEN_BASE / QWEN_UNET on this module.
"""

from __future__ import annotations

import os
from pathlib import Path

from ..canonical_config import try_load_runtime_config

# Tests monkeypatch these. Production leaves them None and reads runtime.json.
QWEN_BASE: Path | None = None
QWEN_UNET: Path | None = None
KREA_BASE: Path | None = None
SD15_BASE: Path | None = None
SD15_CN_BASE: Path | None = None


def adept_config_dir() -> Path:
    override = (os.environ.get("ADEPT_COMFY_CONFIG_DIR") or "").strip()
    if override:
        return Path(override)
    appdata = (os.environ.get("APPDATA") or "").strip()
    if not appdata:
        raise RuntimeError("APPDATA is not set; cannot place Adept Comfy config.")
    return Path(appdata) / "Adept" / "Comfy"


def yaml_path() -> Path:
    return adept_config_dir() / "extra_model_paths.yaml"


def shared_models_dir() -> Path | None:
    local = (os.environ.get("LOCALAPPDATA") or "").strip()
    if not local:
        return None
    path = Path(local) / "Comfy-Desktop" / "ComfyUI-Shared" / "models"
    return path if path.is_dir() else None


def _from_config() -> dict[str, Path | None]:
    cfg = try_load_runtime_config()
    if cfg is None:
        return {}
    qwen = cfg.folder("qwen")
    unet = None
    if qwen is not None:
        for candidate in qwen.rglob("qwen_image_edit_2509*.safetensors"):
            unet = candidate
            break
    return {
        "qwen_base": qwen,
        "qwen_unet": unet,
        "krea": cfg.folder("krea2"),
        "sd15": cfg.folder("sd15"),
        "sd15_cn": cfg.folder("sd15_controlnet"),
    }


def resolved_qwen_base() -> Path | None:
    if QWEN_BASE is not None:
        return Path(QWEN_BASE)
    return _from_config().get("qwen_base")


def resolved_qwen_unet() -> Path | None:
    if QWEN_UNET is not None:
        return Path(QWEN_UNET)
    return _from_config().get("qwen_unet")


def resolved_krea() -> Path | None:
    if KREA_BASE is not None:
        return Path(KREA_BASE)
    return _from_config().get("krea")


def resolved_sd15() -> Path | None:
    if SD15_BASE is not None:
        return Path(SD15_BASE)
    return _from_config().get("sd15")


def resolved_sd15_cn() -> Path | None:
    if SD15_CN_BASE is not None:
        return Path(SD15_CN_BASE)
    return _from_config().get("sd15_cn")


def _block(name: str, base: Path, folders: dict[str, str], *, is_default: bool = False) -> str:
    lines = [f"{name}:", f"  base_path: {str(base).replace(chr(92), '/')}"]
    if is_default:
        lines.append("  is_default: true")
    for key, value in folders.items():
        if "\n" in value:
            lines.append(f"  {key}: |-")
            for part in value.splitlines():
                lines.append(f"    {part}")
        else:
            lines.append(f"  {key}: {value}")
    return "\n".join(lines)


def render_yaml() -> str:
    chunks = [
        "# Generated by Adept Headless Comfy.",
        "# Launch only this Adept file. Never use the Desktop extra-paths file.",
        "# Model roots come from %APPDATA%\\Adept\\Runtime\\runtime.json.",
        "",
    ]
    shared = shared_models_dir()
    if shared is not None:
        chunks.append(
            _block(
                "adept_shared",
                shared,
                {
                    "checkpoints": "checkpoints/",
                    "clip": "clip/",
                    "clip_vision": "clip_vision/",
                    "controlnet": "controlnet/",
                    "diffusion_models": "diffusion_models/",
                    "loras": "loras/",
                    "text_encoders": "text_encoders/",
                    "unet": "unet/",
                    "vae": "vae/",
                    "upscale_models": "upscale_models/",
                },
                is_default=True,
            )
        )
        chunks.append("")
    qwen_base = resolved_qwen_base()
    if qwen_base is not None:
        qwen_folders = {"diffusion_models": "diffusion_models\nsplit_files/diffusion_models"}
        for key, rel in (
            ("text_encoders", "split_files/text_encoders"),
            ("clip", "split_files/text_encoders"),
            ("vae", "split_files/vae"),
        ):
            if (qwen_base / rel.replace("/", os.sep)).is_dir():
                qwen_folders[key] = rel
        chunks.append(_block("adept_qwen_edit_2509", qwen_base, qwen_folders))
    krea = resolved_krea()
    if krea is not None and krea.is_dir():
        chunks.append("")
        chunks.append(
            _block(
                "adept_krea2",
                krea,
                {
                    "checkpoints": ".",
                    "diffusion_models": ".\ndiffusion_models",
                    "text_encoders": "text_encoders",
                    "vae": "vae",
                },
            )
        )
    sd15 = resolved_sd15()
    if sd15 is not None and sd15.is_dir():
        chunks.append("")
        chunks.append(_block("adept_sd15", sd15, {"checkpoints": "."}))
    sd15_cn = resolved_sd15_cn()
    if sd15_cn is not None and sd15_cn.is_dir():
        chunks.append("")
        chunks.append(_block("adept_sd15_controlnet", sd15_cn, {"controlnet": "."}))
    return "\n".join(chunks).rstrip() + "\n"


def validate_required() -> list[str]:
    errors: list[str] = []
    qwen_base = resolved_qwen_base()
    qwen_unet = resolved_qwen_unet()
    if qwen_base is None or not qwen_base.is_dir():
        errors.append("CONFIGURATION ERROR: Qwen Comfy root missing — set modelFolders.qwen in runtime.json")
    if qwen_unet is None or not qwen_unet.is_file():
        errors.append("CONFIGURATION ERROR: Qwen Edit 2509 UNET missing — set modelRoot / modelFolders.qwen")
    return errors


def write_and_validate() -> tuple[Path, list[str]]:
    errors = validate_required()
    if errors:
        return yaml_path(), errors
    dest = yaml_path()
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render_yaml(), encoding="utf-8")
    return dest, []
