import type { VoicePerformanceEmotionPreset } from "../../contracts/voicePerformanceM410";

export const VOICE_PERFORMANCE_EMOTION_PRESETS: VoicePerformanceEmotionPreset[] = [
  {
    id: "quiet-grief",
    name: "Quiet Grief",
    emotionVector: { sadness: 0.82, fear: 0.1, surprise: 0.08 },
    intensity: "low",
    delivery: "hushed, restrained, intimate",
    pacing: "slow with careful spacing",
    breath: "soft catches between phrases",
    notes: "Best for loss held close rather than cried aloud.",
    summary: "Quiet Grief: sadness led, low intensity, hushed, restrained, intimate, slow with careful spacing pacing.",
  },
  {
    id: "contained-anger",
    name: "Contained Anger",
    emotionVector: { anger: 0.7, contempt: 0.2, fear: 0.1 },
    intensity: "medium",
    delivery: "tight, precise, clipped",
    pacing: "measured with firm stops",
    breath: "compressed breath, little air release",
    notes: "Feels controlled and dangerous, not explosive.",
    summary: "Contained Anger: anger led, medium intensity, tight, precise, clipped, measured with firm stops pacing.",
  },
  {
    id: "warm-reassurance",
    name: "Warm Reassurance",
    emotionVector: { joy: 0.62, sadness: 0.14, fear: 0.08, surprise: 0.16 },
    intensity: "low",
    delivery: "gentle, supportive, present",
    pacing: "steady and patient",
    breath: "open breath with easy releases",
    notes: "Comforts without sounding overly cheerful.",
    summary: "Warm Reassurance: joy led, low intensity, gentle, supportive, present, steady and patient pacing.",
  },
  {
    id: "fear-beneath-calm",
    name: "Fear Beneath Calm",
    emotionVector: { fear: 0.58, sadness: 0.17, surprise: 0.25 },
    intensity: "medium",
    delivery: "controlled surface with strain underneath",
    pacing: "steady with slight hesitation",
    breath: "held breath on key words",
    notes: "Outward composure with inner instability.",
    summary: "Fear Beneath Calm: fear led, medium intensity, controlled surface with strain underneath, steady with slight hesitation pacing.",
  },
  {
    id: "embarrassed-sincerity",
    name: "Embarrassed Sincerity",
    emotionVector: { joy: 0.18, fear: 0.32, sadness: 0.1, surprise: 0.4 },
    intensity: "medium",
    delivery: "earnest, slightly flustered",
    pacing: "uneven with self-corrections",
    breath: "small nervous breaths",
    notes: "Honest feeling breaking through social discomfort.",
    summary: "Embarrassed Sincerity: surprise led, medium intensity, earnest, slightly flustered, uneven with self-corrections pacing.",
  },
  {
    id: "defensive-humor",
    name: "Defensive Humor",
    emotionVector: { joy: 0.28, fear: 0.26, contempt: 0.16, surprise: 0.3 },
    intensity: "medium",
    delivery: "quick wit used as cover",
    pacing: "brisk with sharp punch words",
    breath: "light, restless breath",
    notes: "Sounds funny on the surface and guarded underneath.",
    summary: "Defensive Humor: surprise led, medium intensity, quick wit used as cover, brisk with sharp punch words pacing.",
  },
  {
    id: "soft-pleading",
    name: "Soft Pleading",
    emotionVector: { sadness: 0.35, fear: 0.45, joy: 0.2 },
    intensity: "medium",
    delivery: "gentle, vulnerable, reaching",
    pacing: "slower with upward ends",
    breath: "audible breath before requests",
    notes: "Appeals softly rather than desperately.",
    summary: "Soft Pleading: fear led, medium intensity, gentle, vulnerable, reaching, slower with upward ends pacing.",
  },
  {
    id: "growing-panic",
    name: "Growing Panic",
    emotionVector: { fear: 0.68, surprise: 0.22, sadness: 0.1 },
    intensity: "high",
    delivery: "composure slipping line by line",
    pacing: "accelerating with shorter pauses",
    breath: "breath gets tighter as the line continues",
    notes: "Escalates inside the line instead of starting fully panicked.",
    summary: "Growing Panic: fear led, high intensity, composure slipping line by line, accelerating with shorter pauses pacing.",
  },
  {
    id: "cold-authority",
    name: "Cold Authority",
    emotionVector: { contempt: 0.46, anger: 0.34, disgust: 0.2 },
    intensity: "medium",
    delivery: "flat, dominant, unamused",
    pacing: "deliberate and controlled",
    breath: "minimal breath noise",
    notes: "Commands without raising volume.",
    summary: "Cold Authority: contempt led, medium intensity, flat, dominant, unamused, deliberate and controlled pacing.",
  },
  {
    id: "tender-vulnerability",
    name: "Tender Vulnerability",
    emotionVector: { sadness: 0.44, joy: 0.31, fear: 0.25 },
    intensity: "low",
    delivery: "open-hearted, careful, exposed",
    pacing: "slow and attentive",
    breath: "warm open breath",
    notes: "For intimate honesty without melodrama.",
    summary: "Tender Vulnerability: sadness led, low intensity, open-hearted, careful, exposed, slow and attentive pacing.",
  },
  {
    id: "joyful-relief",
    name: "Joyful Relief",
    emotionVector: { joy: 0.66, surprise: 0.22, sadness: 0.12 },
    intensity: "medium",
    delivery: "released, bright, grateful",
    pacing: "easing from quick to settled",
    breath: "breath opens after a held start",
    notes: "The danger passed and the body finally knows it.",
    summary: "Joyful Relief: joy led, medium intensity, released, bright, grateful, easing from quick to settled pacing.",
  },
  {
    id: "exhausted-determination",
    name: "Exhausted Determination",
    emotionVector: { sadness: 0.24, anger: 0.29, fear: 0.17, joy: 0.3 },
    intensity: "medium",
    delivery: "tired but unwilling to stop",
    pacing: "slowed by fatigue, still purposeful",
    breath: "heavy recovery breath between thoughts",
    notes: "Fatigue should be audible without losing resolve.",
    summary: "Exhausted Determination: joy led, medium intensity, tired but unwilling to stop, slowed by fatigue, still purposeful pacing.",
  },
];

export const VOICE_PERFORMANCE_EMOTION_PRESET_LABELS = VOICE_PERFORMANCE_EMOTION_PRESETS.map((preset) => ({
  id: preset.id,
  label: preset.name,
}));
