"""Fill missing M30F locale-pack keys from English + machine-draft phrase map.

Does not overwrite existing translated keys. Runtime UI never calls this.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCALES_DIR = ROOT / "studio-web" / "src" / "i18n" / "locales"
LOCALES = ["fr", "es", "ja", "zh-Hans", "hi", "ru", "pt", "ar", "bn", "id", "ur"]

# Machine-draft phrase table: English source -> locale -> translation.
# Interpolation tokens such as {{count}} must be preserved exactly.
PHRASES: dict[str, dict[str, str]] = {
    "Adept UI": {
        "fr": "Adept UI", "es": "Adept UI", "ja": "Adept UI", "zh-Hans": "Adept UI",
        "hi": "Adept UI", "ru": "Adept UI", "pt": "Adept UI", "ar": "Adept UI",
        "bn": "Adept UI", "id": "Adept UI", "ur": "Adept UI",
    },
    "Save": {"fr": "Enregistrer", "es": "Guardar", "ja": "保存", "zh-Hans": "保存", "hi": "सहेजें", "ru": "Сохранить", "pt": "Salvar", "ar": "حفظ", "bn": "সংরক্ষণ", "id": "Simpan", "ur": "محفوظ کریں"},
    "Cancel": {"fr": "Annuler", "es": "Cancelar", "ja": "キャンセル", "zh-Hans": "取消", "hi": "रद्द करें", "ru": "Отмена", "pt": "Cancelar", "ar": "إلغاء", "bn": "বাতিল", "id": "Batal", "ur": "منسوخ"},
    "Close": {"fr": "Fermer", "es": "Cerrar", "ja": "閉じる", "zh-Hans": "关闭", "hi": "बंद करें", "ru": "Закрыть", "pt": "Fechar", "ar": "إغلاق", "bn": "বন্ধ", "id": "Tutup", "ur": "بند کریں"},
    "Confirm": {"fr": "Confirmer", "es": "Confirmar", "ja": "確認", "zh-Hans": "确认", "hi": "पुष्टि करें", "ru": "Подтвердить", "pt": "Confirmar", "ar": "تأكيد", "bn": "নিশ্চিত", "id": "Konfirmasi", "ur": "تصدیق"},
    "Delete": {"fr": "Supprimer", "es": "Eliminar", "ja": "削除", "zh-Hans": "删除", "hi": "हटाएँ", "ru": "Удалить", "pt": "Excluir", "ar": "حذف", "bn": "মুছুন", "id": "Hapus", "ur": "حذف کریں"},
    "Edit": {"fr": "Modifier", "es": "Editar", "ja": "編集", "zh-Hans": "编辑", "hi": "संपादित करें", "ru": "Изменить", "pt": "Editar", "ar": "تحرير", "bn": "সম্পাদনা", "id": "Edit", "ur": "ترمیم"},
    "Loading…": {"fr": "Chargement…", "es": "Cargando…", "ja": "読み込み中…", "zh-Hans": "加载中…", "hi": "लोड हो रहा है…", "ru": "Загрузка…", "pt": "Carregando…", "ar": "جارٍ التحميل…", "bn": "লোড হচ্ছে…", "id": "Memuat…", "ur": "لوڈ ہو رہا ہے…"},
    "Retry": {"fr": "Réessayer", "es": "Reintentar", "ja": "再試行", "zh-Hans": "重试", "hi": "पुनः प्रयास", "ru": "Повторить", "pt": "Tentar de novo", "ar": "إعادة المحاولة", "bn": "আবার চেষ্টা", "id": "Coba lagi", "ur": "دوبارہ کوشش"},
    "Back": {"fr": "Retour", "es": "Atrás", "ja": "戻る", "zh-Hans": "返回", "hi": "वापस", "ru": "Назад", "pt": "Voltar", "ar": "رجوع", "bn": "পিছনে", "id": "Kembali", "ur": "واپس"},
    "Next": {"fr": "Suivant", "es": "Siguiente", "ja": "次へ", "zh-Hans": "下一步", "hi": "आगे", "ru": "Далее", "pt": "Avançar", "ar": "التالي", "bn": "পরবর্তী", "id": "Berikutnya", "ur": "اگلا"},
    "Search": {"fr": "Rechercher", "es": "Buscar", "ja": "検索", "zh-Hans": "搜索", "hi": "खोजें", "ru": "Поиск", "pt": "Pesquisar", "ar": "بحث", "bn": "অনুসন্ধান", "id": "Cari", "ur": "تلاش"},
    "Language": {"fr": "Langue", "es": "Idioma", "ja": "言語", "zh-Hans": "语言", "hi": "भाषा", "ru": "Язык", "pt": "Idioma", "ar": "اللغة", "bn": "ভাষা", "id": "Bahasa", "ur": "زبان"},
    "Settings": {"fr": "Réglages", "es": "Ajustes", "ja": "設定", "zh-Hans": "设置", "hi": "सेटिंग्स", "ru": "Настройки", "pt": "Configurações", "ar": "الإعدادات", "bn": "সেটিংস", "id": "Pengaturan", "ur": "ترتیبات"},
    "Yes": {"fr": "Oui", "es": "Sí", "ja": "はい", "zh-Hans": "是", "hi": "हाँ", "ru": "Да", "pt": "Sim", "ar": "نعم", "bn": "হ্যাঁ", "id": "Ya", "ur": "ہاں"},
    "No": {"fr": "Non", "es": "No", "ja": "いいえ", "zh-Hans": "否", "hi": "नहीं", "ru": "Нет", "pt": "Não", "ar": "لا", "bn": "না", "id": "Tidak", "ur": "نہیں"},
    "Unknown": {"fr": "Inconnu", "es": "Desconocido", "ja": "不明", "zh-Hans": "未知", "hi": "अज्ञात", "ru": "Неизвестно", "pt": "Desconhecido", "ar": "غير معروف", "bn": "অজানা", "id": "Tidak diketahui", "ur": "نامعلوم"},
    "Copy": {"fr": "Copier", "es": "Copiar", "ja": "コピー", "zh-Hans": "复制", "hi": "कॉपी", "ru": "Копировать", "pt": "Copiar", "ar": "نسخ", "bn": "কপি", "id": "Salin", "ur": "کاپی"},
    "Export": {"fr": "Exporter", "es": "Exportar", "ja": "書き出し", "zh-Hans": "导出", "hi": "निर्यात", "ru": "Экспорт", "pt": "Exportar", "ar": "تصدير", "bn": "রপ্তানি", "id": "Ekspor", "ur": "برآمد"},
    "Import": {"fr": "Importer", "es": "Importar", "ja": "読み込み", "zh-Hans": "导入", "hi": "आयात", "ru": "Импорт", "pt": "Importar", "ar": "استيراد", "bn": "আমদানি", "id": "Impor", "ur": "درآمد"},
    "Refresh": {"fr": "Actualiser", "es": "Actualizar", "ja": "更新", "zh-Hans": "刷新", "hi": "रीफ़्रेश", "ru": "Обновить", "pt": "Atualizar", "ar": "تحديث", "bn": "রিফ্রেশ", "id": "Muat ulang", "ur": "تازہ کریں"},
    "Generate": {"fr": "Générer", "es": "Generar", "ja": "生成", "zh-Hans": "生成", "hi": "जनरेट करें", "ru": "Создать", "pt": "Gerar", "ar": "إنشاء", "bn": "তৈরি করুন", "id": "Hasilkan", "ur": "تیار کریں"},
    "Stop": {"fr": "Arrêter", "es": "Detener", "ja": "停止", "zh-Hans": "停止", "hi": "रोकें", "ru": "Стоп", "pt": "Parar", "ar": "إيقاف", "bn": "থামান", "id": "Berhenti", "ur": "روکیں"},
    "Resume": {"fr": "Reprendre", "es": "Reanudar", "ja": "再開", "zh-Hans": "继续", "hi": "फिर से शुरू", "ru": "Продолжить", "pt": "Retomar", "ar": "استئناف", "bn": "পুনরায় শুরু", "id": "Lanjutkan", "ur": "جاری رکھیں"},
    "Reset": {"fr": "Réinitialiser", "es": "Restablecer", "ja": "リセット", "zh-Hans": "重置", "hi": "रीसेट", "ru": "Сброс", "pt": "Redefinir", "ar": "إعادة تعيين", "bn": "রিসেট", "id": "Reset", "ur": "ری سیٹ"},
    "Add": {"fr": "Ajouter", "es": "Añadir", "ja": "追加", "zh-Hans": "添加", "hi": "जोड़ें", "ru": "Добавить", "pt": "Adicionar", "ar": "إضافة", "bn": "যোগ", "id": "Tambah", "ur": "شامل کریں"},
    "Remove": {"fr": "Retirer", "es": "Quitar", "ja": "取り除く", "zh-Hans": "移除", "hi": "हटाएँ", "ru": "Убрать", "pt": "Remover", "ar": "إزالة", "bn": "সরান", "id": "Hapus", "ur": "ہٹائیں"},
    "Replace": {"fr": "Remplacer", "es": "Reemplazar", "ja": "置き換え", "zh-Hans": "替换", "hi": "बदलें", "ru": "Заменить", "pt": "Substituir", "ar": "استبدال", "bn": "প্রতিস্থাপন", "id": "Ganti", "ur": "بدلें"},
    "Rename": {"fr": "Renommer", "es": "Renombrar", "ja": "名前を変更", "zh-Hans": "重命名", "hi": "नाम बदलें", "ru": "Переименовать", "pt": "Renomear", "ar": "إعادة تسمية", "bn": "নাম পরিবর্তন", "id": "Ubah nama", "ur": "نام تبدیل کریں"},
    "Select": {"fr": "Sélectionner", "es": "Seleccionar", "ja": "選択", "zh-Hans": "选择", "hi": "चुनें", "ru": "Выбрать", "pt": "Selecionar", "ar": "تحديد", "bn": "নির্বাচন", "id": "Pilih", "ur": "منتخب کریں"},
    "Upload": {"fr": "Téléverser", "es": "Subir", "ja": "アップロード", "zh-Hans": "上传", "hi": "अपलोड", "ru": "Загрузить", "pt": "Enviar", "ar": "رفع", "bn": "আপলোড", "id": "Unggah", "ur": "اپ لوڈ"},
    "Apply": {"fr": "Appliquer", "es": "Aplicar", "ja": "適用", "zh-Hans": "应用", "hi": "लागू करें", "ru": "Применить", "pt": "Aplicar", "ar": "تطبيق", "bn": "প্রয়োগ", "id": "Terapkan", "ur": "لاگو کریں"},
    "Open": {"fr": "Ouvrir", "es": "Abrir", "ja": "開く", "zh-Hans": "打开", "hi": "खोलें", "ru": "Открыть", "pt": "Abrir", "ar": "فتح", "bn": "খুলুন", "id": "Buka", "ur": "کھولیں"},
    "Pause": {"fr": "Pause", "es": "Pausa", "ja": "一時停止", "zh-Hans": "暂停", "hi": "विराम", "ru": "Пауза", "pt": "Pausar", "ar": "إيقاف مؤقت", "bn": "বিরতি", "id": "Jeda", "ur": "وقفہ"},
    "Play": {"fr": "Lecture", "es": "Reproducir", "ja": "再生", "zh-Hans": "播放", "hi": "चलाएँ", "ru": "Воспроизвести", "pt": "Reproduzir", "ar": "تشغيل", "bn": "চালান", "id": "Putar", "ur": "چلائیں"},
    "Done": {"fr": "Terminé", "es": "Listo", "ja": "完了", "zh-Hans": "完成", "hi": "हो गया", "ru": "Готово", "pt": "Concluído", "ar": "تم", "bn": "সম্পন্ন", "id": "Selesai", "ur": "مکمل"},
    "More": {"fr": "Plus", "es": "Más", "ja": "その他", "zh-Hans": "更多", "hi": "और", "ru": "Ещё", "pt": "Mais", "ar": "المزيد", "bn": "আরও", "id": "Lainnya", "ur": "مزید"},
    "Advanced": {"fr": "Avancé", "es": "Avanzado", "ja": "詳細", "zh-Hans": "高级", "hi": "उन्नत", "ru": "Дополнительно", "pt": "Avançado", "ar": "متقدم", "bn": "উন্নত", "id": "Lanjutan", "ur": "جدید"},
    "Help": {"fr": "Aide", "es": "Ayuda", "ja": "ヘルプ", "zh-Hans": "帮助", "hi": "मदद", "ru": "Справка", "pt": "Ajuda", "ar": "مساعدة", "bn": "সাহায্য", "id": "Bantuan", "ur": "مدد"},
    "{{count}} selected": {"fr": "{{count}} sélectionné(s)", "es": "{{count}} seleccionados", "ja": "{{count}} 件選択", "zh-Hans": "已选择 {{count}} 项", "hi": "{{count}} चयनित", "ru": "Выбрано: {{count}}", "pt": "{{count}} selecionados", "ar": "{{count}} محدد", "bn": "{{count}} নির্বাচিত", "id": "{{count}} dipilih", "ur": "{{count}} منتخب"},
    "{{count}} asset": {"fr": "{{count}} fichier", "es": "{{count}} archivo", "ja": "{{count}} 件の素材", "zh-Hans": "{{count}} 个素材", "hi": "{{count}} एसेट", "ru": "{{count}} ресурс", "pt": "{{count}} arquivo", "ar": "أصل {{count}}", "bn": "{{count}} অ্যাসেট", "id": "{{count}} aset", "ur": "{{count}} اثاثہ"},
    "{{count}} assets": {"fr": "{{count}} fichiers", "es": "{{count}} archivos", "ja": "{{count}} 件の素材", "zh-Hans": "{{count}} 个素材", "hi": "{{count}} एसेट", "ru": "{{count}} ресурсов", "pt": "{{count}} arquivos", "ar": "{{count}} أصول", "bn": "{{count}} অ্যাসেট", "id": "{{count}} aset", "ur": "{{count}} اثاثے"},
    "{{count}} reference": {"fr": "{{count}} référence", "es": "{{count}} referencia", "ja": "{{count}} 件の参照", "zh-Hans": "{{count}} 个参考", "hi": "{{count}} संदर्भ", "ru": "{{count}} ссылка", "pt": "{{count}} referência", "ar": "مرجع {{count}}", "bn": "{{count}} রেফারেন্স", "id": "{{count}} referensi", "ur": "{{count}} حوالہ"},
    "{{count}} references": {"fr": "{{count}} références", "es": "{{count}} referencias", "ja": "{{count}} 件の参照", "zh-Hans": "{{count}} 个参考", "hi": "{{count}} संदर्भ", "ru": "{{count}} ссылок", "pt": "{{count}} referências", "ar": "{{count}} مراجع", "bn": "{{count}} রেফারেন্স", "id": "{{count}} referensi", "ur": "{{count}} حوالے"},
    "Delete \"{{name}}\"?": {"fr": "Supprimer « {{name}} » ?", "es": "¿Eliminar «{{name}}»?", "ja": "「{{name}}」を削除しますか？", "zh-Hans": "删除“{{name}}”？", "hi": "\"{{name}}\" हटाएँ?", "ru": "Удалить «{{name}}»?", "pt": "Excluir \"{{name}}\"?", "ar": "هل تريد حذف \"{{name}}\"؟", "bn": "\"{{name}}\" মুছবেন?", "id": "Hapus \"{{name}}\"?", "ur": "\"{{name}}\" حذف کریں؟"},
    "Saved": {"fr": "Enregistré", "es": "Guardado", "ja": "保存しました", "zh-Hans": "已保存", "hi": "सहेजा गया", "ru": "Сохранено", "pt": "Salvo", "ar": "تم الحفظ", "bn": "সংরক্ষিত", "id": "Tersimpan", "ur": "محفوظ ہو گیا"},
    "Uploaded": {"fr": "Téléversé", "es": "Subido", "ja": "アップロードしました", "zh-Hans": "已上传", "hi": "अपलोड हुआ", "ru": "Загружено", "pt": "Enviado", "ar": "تم الرفع", "bn": "আপলোড হয়েছে", "id": "Terunggah", "ur": "اپ لوڈ ہو گیا"},
    "Generated": {"fr": "Généré", "es": "Generado", "ja": "生成しました", "zh-Hans": "已生成", "hi": "जनरेट हुआ", "ru": "Создано", "pt": "Gerado", "ar": "تم الإنشاء", "bn": "তৈরি হয়েছে", "id": "Dihasilkan", "ur": "تیار ہو گیا"},
    "Deleted": {"fr": "Supprimé", "es": "Eliminado", "ja": "削除しました", "zh-Hans": "已删除", "hi": "हटाया गया", "ru": "Удалено", "pt": "Excluído", "ar": "تم الحذف", "bn": "মুছে ফেলা হয়েছে", "id": "Dihapus", "ur": "حذف ہو گیا"},
    "Moved": {"fr": "Déplacé", "es": "Movido", "ja": "移動しました", "zh-Hans": "已移动", "hi": "स्थानांतरित", "ru": "Перемещено", "pt": "Movido", "ar": "تم النقل", "bn": "সরানো হয়েছে", "id": "Dipindahkan", "ur": "منتقل ہو گیا"},
    "Unsupported": {"fr": "Non pris en charge", "es": "No compatible", "ja": "未対応", "zh-Hans": "不支持", "hi": "असमर्थित", "ru": "Не поддерживается", "pt": "Não suportado", "ar": "غير مدعوم", "bn": "অসমর্থিত", "id": "Tidak didukung", "ur": "غیر معاون"},
    "Not run yet": {"fr": "Pas encore exécuté", "es": "Aún no ejecutado", "ja": "未実行", "zh-Hans": "尚未运行", "hi": "अभी नहीं चला", "ru": "Ещё не запускалось", "pt": "Ainda não executado", "ar": "لم يُشغَّل بعد", "bn": "এখনও চালানো হয়নি", "id": "Belum dijalankan", "ur": "ابھی نہیں چلا"},
    "Ready": {"fr": "Prêt", "es": "Listo", "ja": "準備完了", "zh-Hans": "就绪", "hi": "तैयार", "ru": "Готово", "pt": "Pronto", "ar": "جاهز", "bn": "প্রস্তুত", "id": "Siap", "ur": "تیار"},
    "General": {"fr": "Général", "es": "General", "ja": "一般", "zh-Hans": "常规", "hi": "सामान्य", "ru": "Общие", "pt": "Geral", "ar": "عام", "bn": "সাধারণ", "id": "Umum", "ur": "عام"},
    "AI Learning": {"fr": "Apprentissage IA", "es": "Aprendizaje de IA", "ja": "AI 学習", "zh-Hans": "AI 学习", "hi": "AI सीख", "ru": "Обучение ИИ", "pt": "Aprendizado de IA", "ar": "تعلم الذكاء الاصطناعي", "bn": "এআই শেখা", "id": "Pembelajaran AI", "ur": "اے آئی سیکھنا"},
    "Defaults": {"fr": "Valeurs par défaut", "es": "Valores predeterminados", "ja": "既定値", "zh-Hans": "默认值", "hi": "डिफ़ॉल्ट", "ru": "По умолчанию", "pt": "Padrões", "ar": "افتراضي", "bn": "ডিফল্ট", "id": "Default", "ur": "طے شدہ"},
    "Library": {"fr": "Bibliothèque", "es": "Biblioteca", "ja": "ライブラリ", "zh-Hans": "资料库", "hi": "लाइब्रेरी", "ru": "Библиотека", "pt": "Biblioteca", "ar": "المكتبة", "bn": "লাইব্রেরি", "id": "Pustaka", "ur": "لائبریری"},
    "AI Providers": {"fr": "Fournisseurs d’IA", "es": "Proveedores de IA", "ja": "AI プロバイダー", "zh-Hans": "AI 提供方", "hi": "AI प्रदाता", "ru": "Провайдеры ИИ", "pt": "Provedores de IA", "ar": "مزودو الذكاء الاصطناعي", "bn": "এআই প্রদানকারী", "id": "Penyedia AI", "ur": "اے آئی فراہم کنندگان"},
    "Rendering": {"fr": "Rendu", "es": "Renderizado", "ja": "レンダリング", "zh-Hans": "渲染", "hi": "रेंडरिंग", "ru": "Рендеринг", "pt": "Renderização", "ar": "العرض", "bn": "রেন্ডারিং", "id": "Render", "ur": "رینڈرنگ"},
    "Collaboration": {"fr": "Collaboration", "es": "Colaboración", "ja": "共同作業", "zh-Hans": "协作", "hi": "सहयोग", "ru": "Совместная работа", "pt": "Colaboração", "ar": "تعاون", "bn": "সহযোগিতা", "id": "Kolaborasi", "ur": "تعاون"},
    "Interface language": {"fr": "Langue de l’interface", "es": "Idioma de la interfaz", "ja": "インターフェース言語", "zh-Hans": "界面语言", "hi": "इंटरफ़ेस भाषा", "ru": "Язык интерфейса", "pt": "Idioma da interface", "ar": "لغة الواجهة", "bn": "ইন্টারফেস ভাষা", "id": "Bahasa antarmuka", "ur": "انٹرفیس کی زبان"},
    "Co-Director conversation language": {"fr": "Langue de conversation du Co-Director", "es": "Idioma de conversación de Co-Director", "ja": "Co-Director の会話言語", "zh-Hans": "Co-Director 对话语言", "hi": "Co-Director बातचीत की भाषा", "ru": "Язык общения Co-Director", "pt": "Idioma da conversa do Co-Director", "ar": "لغة محادثة Co-Director", "bn": "Co-Director কথোপকথনের ভাষা", "id": "Bahasa percakapan Co-Director", "ur": "Co-Director گفتگو کی زبان"},
    "Project primary language": {"fr": "Langue principale du projet", "es": "Idioma principal del proyecto", "ja": "プロジェクトの主言語", "zh-Hans": "项目主要语言", "hi": "प्रोजेक्ट की मुख्य भाषा", "ru": "Основной язык проекта", "pt": "Idioma principal do projeto", "ar": "اللغة الأساسية للمشروع", "bn": "প্রকল্পের প্রধান ভাষা", "id": "Bahasa utama proyek", "ur": "پروجیکٹ کی بنیادی زبان"},
    "Generation prompt language policy": {"fr": "Politique linguistique des prompts de génération", "es": "Política de idioma de los prompts de generación", "ja": "生成プロンプトの言語ポリシー", "zh-Hans": "生成提示语言策略", "hi": "जनरेशन प्रॉम्प्ट भाषा नीति", "ru": "Языковая политика промптов", "pt": "Política de idioma dos prompts", "ar": "سياسة لغة أوامر التوليد", "bn": "জেনারেশন প্রম্পট ভাষা নীতি", "id": "Kebijakan bahasa prompt generasi", "ur": "جنریشن پرامپٹ زبان کی پالیسی"},
    "Export language": {"fr": "Langue d’export", "es": "Idioma de exportación", "ja": "書き出し言語", "zh-Hans": "导出语言", "hi": "निर्यात भाषा", "ru": "Язык экспорта", "pt": "Idioma de exportação", "ar": "لغة التصدير", "bn": "রপ্তানি ভাষা", "id": "Bahasa ekspor", "ur": "برآمد کی زبان"},
    "Auto": {"fr": "Auto", "es": "Automático", "ja": "自動", "zh-Hans": "自动", "hi": "स्वतः", "ru": "Авто", "pt": "Automático", "ar": "تلقائي", "bn": "স্বয়ংক্রিয়", "id": "Otomatis", "ur": "خودکار"},
    "User language": {"fr": "Langue de l’utilisateur", "es": "Idioma del usuario", "ja": "ユーザー言語", "zh-Hans": "用户语言", "hi": "उपयोगकर्ता भाषा", "ru": "Язык пользователя", "pt": "Idioma do usuário", "ar": "لغة المستخدم", "bn": "ব্যবহারকারীর ভাষা", "id": "Bahasa pengguna", "ur": "صارف کی زبان"},
    "English": {"fr": "Anglais", "es": "Inglés", "ja": "英語", "zh-Hans": "英语", "hi": "अंग्रेज़ी", "ru": "Английский", "pt": "Inglês", "ar": "الإنجليزية", "bn": "ইংরেজি", "id": "Inggris", "ur": "انگریزی"},
    "Project canonical": {"fr": "Langue canonique du projet", "es": "Canónico del proyecto", "ja": "プロジェクトの正規言語", "zh-Hans": "项目规范语言", "hi": "प्रोजेक्ट कैननिकल", "ru": "Канонический язык проекта", "pt": "Canônico do projeto", "ar": "اللغة المعيارية للمشروع", "bn": "প্রকল্প ক্যাননিকাল", "id": "Kanonik proyek", "ur": "پروجیکٹ کیننیکل"},
    "Bilingual (English + Simplified Chinese)": {"fr": "Bilingue (anglais + chinois simplifié)", "es": "Bilingüe (inglés + chino simplificado)", "ja": "バイリンガル（英語＋簡体字中国語）", "zh-Hans": "双语（英语 + 简体中文）", "hi": "द्विभाषी (अंग्रेज़ी + सरलीकृत चीनी)", "ru": "Двуязычный (английский + упрощённый китайский)", "pt": "Bilíngue (inglês + chinês simplificado)", "ar": "ثنائي اللغة (الإنجليزية + الصينية المبسطة)", "bn": "দ্বিভাষিক (ইংরেজি + সরলীকৃত চীনা)", "id": "Bilingual (Inggris + Tionghoa Sederhana)", "ur": "دو لسانی (انگریزی + آسان چینی)"},
    "No translation": {"fr": "Pas de traduction", "es": "Sin traducción", "ja": "翻訳しない", "zh-Hans": "不翻译", "hi": "अनुवाद नहीं", "ru": "Без перевода", "pt": "Sem tradução", "ar": "بدون ترجمة", "bn": "অনুবাদ নয়", "id": "Tanpa terjemahan", "ur": "ترجمہ نہیں"},
    "Name": {"fr": "Nom", "es": "Nombre", "ja": "名前", "zh-Hans": "名称", "hi": "नाम", "ru": "Имя", "pt": "Nome", "ar": "الاسم", "bn": "নাম", "id": "Nama", "ur": "نام"},
    "Description": {"fr": "Description", "es": "Descripción", "ja": "説明", "zh-Hans": "描述", "hi": "विवरण", "ru": "Описание", "pt": "Descrição", "ar": "الوصف", "bn": "বিবরণ", "id": "Deskripsi", "ur": "تفصیل"},
    "Company": {"fr": "Société", "es": "Empresa", "ja": "会社", "zh-Hans": "公司", "hi": "कंपनी", "ru": "Компания", "pt": "Empresa", "ar": "الشركة", "bn": "কোম্পানি", "id": "Perusahaan", "ur": "کمپنی"},
    "Director": {"fr": "Réalisateur", "es": "Director", "ja": "監督", "zh-Hans": "导演", "hi": "निर्देशक", "ru": "Режиссёр", "pt": "Diretor", "ar": "المخرج", "bn": "পরিচালক", "id": "Sutradara", "ur": "ڈائریکٹر"},
    "Version": {"fr": "Version", "es": "Versión", "ja": "バージョン", "zh-Hans": "版本", "hi": "संस्करण", "ru": "Версия", "pt": "Versão", "ar": "الإصدار", "bn": "সংস্করণ", "id": "Versi", "ur": "ورژن"},
    "Timeline Generator": {"fr": "Générateur de timeline", "es": "Generador de timeline", "ja": "タイムラインジェネレーター", "zh-Hans": "时间线生成器", "hi": "टाइमलाइन जनरेटर", "ru": "Генератор таймлайна", "pt": "Gerador de timeline", "ar": "مولّد الخط الزمني", "bn": "টাইমলাইন জেনারেটর", "id": "Generator Timeline", "ur": "ٹائم لائن جنریٹر"},
    "Scene": {"fr": "Scène", "es": "Escena", "ja": "シーン", "zh-Hans": "场景", "hi": "सीन", "ru": "Сцена", "pt": "Cena", "ar": "المشهد", "bn": "দৃশ্য", "id": "Adegan", "ur": "سین"},
    "Preview Monitor": {"fr": "Moniteur d’aperçu", "es": "Monitor de vista previa", "ja": "プレビューモニター", "zh-Hans": "预览监视器", "hi": "प्रीव्यू मॉनिटर", "ru": "Монитор предпросмотра", "pt": "Monitor de prévia", "ar": "شاشة المعاينة", "bn": "প্রিভিউ মনিটর", "id": "Monitor Pratinjau", "ur": "پیش منظر مانیٹر"},
    "References": {"fr": "Références", "es": "Referencias", "ja": "参照", "zh-Hans": "参考", "hi": "संदर्भ", "ru": "Ссылки", "pt": "Referências", "ar": "المراجع", "bn": "রেফারেন্স", "id": "Referensi", "ur": "حوالہ جات"},
    "Inspector": {"fr": "Inspecteur", "es": "Inspector", "ja": "インスペクター", "zh-Hans": "检查器", "hi": "इंस्पेक्टर", "ru": "Инспектор", "pt": "Inspetor", "ar": "المفتش", "bn": "ইন্সপেক্টর", "id": "Inspektur", "ur": "انسپکٹر"},
    "Co-Director": {"fr": "Co-Director", "es": "Co-Director", "ja": "Co-Director", "zh-Hans": "Co-Director", "hi": "Co-Director", "ru": "Co-Director", "pt": "Co-Director", "ar": "Co-Director", "bn": "Co-Director", "id": "Co-Director", "ur": "Co-Director"},
    "Fit": {"fr": "Ajuster", "es": "Ajustar", "ja": "フィット", "zh-Hans": "适应", "hi": "फ़िट", "ru": "Вписать", "pt": "Ajustar", "ar": "ملاءمة", "bn": "ফিট", "id": "Pas", "ur": "فٹ"},
    "Viewer Size": {"fr": "Taille du viewer", "es": "Tamaño del visor", "ja": "ビューアーサイズ", "zh-Hans": "查看器大小", "hi": "व्यूअर आकार", "ru": "Размер просмотра", "pt": "Tamanho do visualizador", "ar": "حجم العارض", "bn": "ভিউয়ার আকার", "id": "Ukuran penampil", "ur": "ویوئر سائز"},
    "Large": {"fr": "Grand", "es": "Grande", "ja": "大", "zh-Hans": "大", "hi": "बड़ा", "ru": "Крупный", "pt": "Grande", "ar": "كبير", "bn": "বড়", "id": "Besar", "ur": "بڑا"},
    "Balanced": {"fr": "Équilibré", "es": "Equilibrado", "ja": "バランス", "zh-Hans": "均衡", "hi": "संतुलित", "ru": "Сбалансированный", "pt": "Equilibrado", "ar": "متوازن", "bn": "ভারসাম্য", "id": "Seimbang", "ur": "متوازن"},
    "Timeline Focus": {"fr": "Priorité timeline", "es": "Enfoque en timeline", "ja": "タイムライン重視", "zh-Hans": "时间线优先", "hi": "टाइमलाइन फोकस", "ru": "Фокус на таймлайн", "pt": "Foco na timeline", "ar": "تركيز الخط الزمني", "bn": "টাইমলাইন ফোকাস", "id": "Fokus timeline", "ur": "ٹائم لائن فوکس"},
    "Picture Shape": {"fr": "Format d’image", "es": "Forma de imagen", "ja": "画面比率", "zh-Hans": "画面比例", "hi": "चित्र आकार", "ru": "Формат кадра", "pt": "Formato da imagem", "ar": "شكل الصورة", "bn": "ছবির আকৃতি", "id": "Bentuk gambar", "ur": "تصویر کی شکل"},
    "Guides": {"fr": "Guides", "es": "Guías", "ja": "ガイド", "zh-Hans": "参考线", "hi": "गाइड", "ru": "Направляющие", "pt": "Guias", "ar": "الأدلة", "bn": "গাইড", "id": "Panduan", "ur": "رہنما خطوط"},
    "Pause viewer": {"fr": "Mettre le viewer en pause", "es": "Pausar visor", "ja": "ビューアーを一時停止", "zh-Hans": "暂停查看器", "hi": "व्यूअर रोकें", "ru": "Пауза просмотра", "pt": "Pausar visualizador", "ar": "إيقاف العارض", "bn": "ভিউয়ার থামান", "id": "Jeda penampil", "ur": "ویوئر روکیں"},
    "Resume viewer": {"fr": "Reprendre le viewer", "es": "Reanudar visor", "ja": "ビューアーを再開", "zh-Hans": "继续查看器", "hi": "व्यूअर फिर चलाएँ", "ru": "Возобновить просмотр", "pt": "Retomar visualizador", "ar": "استئناف العارض", "bn": "ভিউয়ার চালু", "id": "Lanjut penampil", "ur": "ویوئر جاری"},
    "Reset Layout": {"fr": "Réinitialiser la disposition", "es": "Restablecer diseño", "ja": "レイアウトをリセット", "zh-Hans": "重置布局", "hi": "लेआउट रीसेट", "ru": "Сбросить макет", "pt": "Redefinir layout", "ar": "إعادة تعيين التخطيط", "bn": "লেআউট রিসেট", "id": "Reset tata letak", "ur": "لے آؤٹ ری سیٹ"},
    "Generate Scene": {"fr": "Générer la scène", "es": "Generar escena", "ja": "シーンを生成", "zh-Hans": "生成场景", "hi": "सीन जनरेट करें", "ru": "Создать сцену", "pt": "Gerar cena", "ar": "إنشاء المشهد", "bn": "দৃশ্য তৈরি করুন", "id": "Hasilkan adegan", "ur": "سین تیار کریں"},
    "Stop Jobs": {"fr": "Arrêter les tâches", "es": "Detener trabajos", "ja": "ジョブを停止", "zh-Hans": "停止任务", "hi": "जॉब रोकें", "ru": "Остановить задачи", "pt": "Parar trabalhos", "ar": "إيقاف المهام", "bn": "জব থামান", "id": "Hentikan pekerjaan", "ur": "جاب روکیں"},
    "Image Planning": {"fr": "Planification image", "es": "Planificación de imagen", "ja": "画像プランニング", "zh-Hans": "图像规划", "hi": "इमेज प्लानिंग", "ru": "Планирование изображения", "pt": "Planejamento de imagem", "ar": "تخطيط الصورة", "bn": "ইমেজ প্ল্যানিং", "id": "Perencanaan gambar", "ur": "امیج پلاننگ"},
    "Video Finishing": {"fr": "Finition vidéo", "es": "Acabado de video", "ja": "ビデオ仕上げ", "zh-Hans": "视频成片", "hi": "वीडियो फ़िनिशिंग", "ru": "Видео-финиш", "pt": "Finalização de vídeo", "ar": "إنهاء الفيديو", "bn": "ভিডিও ফিনিশিং", "id": "Penyelesaian video", "ur": "ویڈیو فنشنگ"},
    "Preflight": {"fr": "Prévol", "es": "Preflight", "ja": "プリフライト", "zh-Hans": "预检", "hi": "प्रीफ़्लाइट", "ru": "Предпроверка", "pt": "Pré-checagem", "ar": "الفحص المسبق", "bn": "প্রিফ্লাইট", "id": "Pra-pemeriksaan", "ur": "پری فلائٹ"},
    "IMAGE REFERENCE": {"fr": "RÉFÉRENCE IMAGE", "es": "REFERENCIA DE IMAGEN", "ja": "イメージ参照", "zh-Hans": "图像参考", "hi": "इमेज संदर्भ", "ru": "ИЗОБРАЖЕНИЕ-ССЫЛКА", "pt": "REFERÊNCIA DE IMAGEM", "ar": "مرجع صورة", "bn": "ইমেজ রেফারেন্স", "id": "REFERENSI GAMBAR", "ur": "تصویری حوالہ"},
    "VIDEO REFERENCE": {"fr": "RÉFÉRENCE VIDÉO", "es": "REFERENCIA DE VIDEO", "ja": "ビデオ参照", "zh-Hans": "视频参考", "hi": "वीडियो संदर्भ", "ru": "ВИДЕО-ССЫЛКА", "pt": "REFERÊNCIA DE VÍDEO", "ar": "مرجع فيديو", "bn": "ভিডিও রেফারেন্স", "id": "REFERENSI VIDEO", "ur": "ویڈیو حوالہ"},
    "Add to Timeline": {"fr": "Ajouter à la timeline", "es": "Añadir a la timeline", "ja": "タイムラインに追加", "zh-Hans": "添加到时间线", "hi": "टाइमलाइन में जोड़ें", "ru": "Добавить на таймлайн", "pt": "Adicionar à timeline", "ar": "إضافة إلى الخط الزمني", "bn": "টাইমলাইনে যোগ", "id": "Tambah ke timeline", "ur": "ٹائم لائن میں شامل"},
    "Add to References": {"fr": "Ajouter aux références", "es": "Añadir a referencias", "ja": "参照に追加", "zh-Hans": "添加到参考", "hi": "संदर्भ में जोड़ें", "ru": "Добавить в ссылки", "pt": "Adicionar às referências", "ar": "إضافة إلى المراجع", "bn": "রেফারেন্সে যোগ", "id": "Tambah ke referensi", "ur": "حوالوں میں شامل"},
    "Search Library": {"fr": "Rechercher dans la bibliothèque", "es": "Buscar en la biblioteca", "ja": "ライブラリを検索", "zh-Hans": "搜索资料库", "hi": "लाइब्रेरी खोजें", "ru": "Поиск в библиотеке", "pt": "Pesquisar biblioteca", "ar": "البحث في المكتبة", "bn": "লাইব্রেরি খুঁজুন", "id": "Cari pustaka", "ur": "لائبریری تلاش"},
    "All": {"fr": "Tout", "es": "Todo", "ja": "すべて", "zh-Hans": "全部", "hi": "सभी", "ru": "Все", "pt": "Tudo", "ar": "الكل", "bn": "সব", "id": "Semua", "ur": "سب"},
    "Images": {"fr": "Images", "es": "Imágenes", "ja": "画像", "zh-Hans": "图像", "hi": "छवियाँ", "ru": "Изображения", "pt": "Imagens", "ar": "صور", "bn": "ছবি", "id": "Gambar", "ur": "تصاویر"},
    "Video": {"fr": "Vidéo", "es": "Video", "ja": "ビデオ", "zh-Hans": "视频", "hi": "वीडियो", "ru": "Видео", "pt": "Vídeo", "ar": "فيديو", "bn": "ভিডিও", "id": "Video", "ur": "ویڈیو"},
    "Audio": {"fr": "Audio", "es": "Audio", "ja": "オーディオ", "zh-Hans": "音频", "hi": "ऑडियो", "ru": "Аудио", "pt": "Áudio", "ar": "صوت", "bn": "অডিও", "id": "Audio", "ur": "آڈیو"},
    "Documents": {"fr": "Documents", "es": "Documentos", "ja": "ドキュメント", "zh-Hans": "文档", "hi": "दस्तावेज़", "ru": "Документы", "pt": "Documentos", "ar": "مستندات", "bn": "নথি", "id": "Dokumen", "ur": "دستاویزات"},
    "Open Co-Director": {"fr": "Ouvrir Co-Director", "es": "Abrir Co-Director", "ja": "Co-Director を開く", "zh-Hans": "打开 Co-Director", "hi": "Co-Director खोलें", "ru": "Открыть Co-Director", "pt": "Abrir Co-Director", "ar": "فتح Co-Director", "bn": "Co-Director খুলুন", "id": "Buka Co-Director", "ur": "Co-Director کھولیں"},
    "Scene Creator": {"fr": "Créateur de scènes", "es": "Creador de escenas", "ja": "シーンクリエイター", "zh-Hans": "场景创作", "hi": "सीन क्रिएटर", "ru": "Создание сцен", "pt": "Criador de cenas", "ar": "منشئ المشاهد", "bn": "সিন ক্রিয়েটর", "id": "Pembuat Adegan", "ur": "سین تخلیق کار"},
    "Scenes": {"fr": "Scènes", "es": "Escenas", "ja": "シーン", "zh-Hans": "场景", "hi": "सीन", "ru": "Сцены", "pt": "Cenas", "ar": "المشاهد", "bn": "দৃশ্যসমূহ", "id": "Adegan", "ur": "سینز"},
    "Shots": {"fr": "Plans", "es": "Tomas", "ja": "ショット", "zh-Hans": "镜头", "hi": "शॉट", "ru": "Кажры", "pt": "Takes", "ar": "اللقطات", "bn": "শট", "id": "Shot", "ur": "شاٹس"},
    "New Shot": {"fr": "Nouveau plan", "es": "Nueva toma", "ja": "新しいショット", "zh-Hans": "新建镜头", "hi": "नया शॉट", "ru": "Новый кадр", "pt": "Novo take", "ar": "لقطة جديدة", "bn": "নতুন শট", "id": "Shot baru", "ur": "نیا شاٹ"},
    "Spatial Profile": {"fr": "Profil spatial", "es": "Perfil espacial", "ja": "空間プロファイル", "zh-Hans": "空间配置", "hi": "स्पेशियल प्रोफ़ाइल", "ru": "Пространственный профиль", "pt": "Perfil espacial", "ar": "الملف المكاني", "bn": "স্পেশিয়াল প্রোফাইল", "id": "Profil spasial", "ur": "اسپیشل پروفائل"},
    "Reset Workspace": {"fr": "Réinitialiser l’espace de travail", "es": "Restablecer espacio de trabajo", "ja": "ワークスペースをリセット", "zh-Hans": "重置工作区", "hi": "वर्कस्पेस रीसेट", "ru": "Сбросить рабочее пространство", "pt": "Redefinir espaço de trabalho", "ar": "إعادة تعيين مساحة العمل", "bn": "ওয়ার্কস্পেস রিসেট", "id": "Reset ruang kerja", "ur": "ورک اسپیس ری سیٹ"},
    "3D Camera Orientation": {"fr": "Orientation caméra 3D", "es": "Orientación de cámara 3D", "ja": "3Dカメラの向き", "zh-Hans": "3D 相机朝向", "hi": "3D कैमरा ओरिएंटेशन", "ru": "Ориентация 3D-камеры", "pt": "Orientação da câmera 3D", "ar": "اتجاه الكاميرا ثلاثية الأبعاد", "bn": "৩ডি ক্যামেরা ওরিয়েন্টেশন", "id": "Orientasi kamera 3D", "ur": "3D کیمرہ رخ"},
    "Inpaint / Region Edit": {"fr": "Inpaint / édition de région", "es": "Inpaint / edición de región", "ja": "インペイント / 領域編集", "zh-Hans": "局部重绘 / 区域编辑", "hi": "इनपेंट / क्षेत्र संपादन", "ru": "Inpaint / правка области", "pt": "Inpaint / edição de região", "ar": "طلاء داخلي / تحرير المنطقة", "bn": "ইনপেইন্ট / অঞ্চল সম্পাদনা", "id": "Inpaint / edit wilayah", "ur": "ان پینٹ / علاقہ ترمیم"},
    "Generate Low-Res Preview": {"fr": "Générer un aperçu basse résolution", "es": "Generar vista previa de baja resolución", "ja": "低解像度プレビューを生成", "zh-Hans": "生成低分辨率预览", "hi": "लो-रेज़ प्रीव्यू जनरेट करें", "ru": "Создать превью низкого разрешения", "pt": "Gerar prévia em baixa resolução", "ar": "إنشاء معاينة منخفضة الدقة", "bn": "লো-রেজ প্রিভিউ তৈরি", "id": "Hasilkan pratinjau resolusi rendah", "ur": "کم ریزولوشن پیش منظر بنائیں"},
    "Final Quality Render": {"fr": "Rendu qualité finale", "es": "Render de calidad final", "ja": "最終品質レンダー", "zh-Hans": "最终质量渲染", "hi": "अंतिम गुणवत्ता रेंडर", "ru": "Финальный рендер", "pt": "Render de qualidade final", "ar": "عرض الجودة النهائية", "bn": "চূড়ান্ত মানের রেন্ডার", "id": "Render kualitas akhir", "ur": "حتمی کوالٹی رینڈر"},
    "Cinematic Image Generator": {"fr": "Générateur d’images cinématographiques", "es": "Generador de imagen cinematográfica", "ja": "シネマティック画像ジェネレーटर", "zh-Hans": "电影级图像生成器", "hi": "सिनेमैटिक इमेज जनरेटर", "ru": "Кинематографический генератор изображений", "pt": "Gerador de imagem cinematográfica", "ar": "مولّد الصور السينمائية", "bn": "সিনেমাটিক ইমেজ জেনারেটর", "id": "Generator gambar sinematik", "ur": "سینمائی تصویر جنریٹر"},
    "Image Plan": {"fr": "Plan image", "es": "Plan de imagen", "ja": "画像プラン", "zh-Hans": "图像计划", "hi": "इमेज प्लान", "ru": "План изображения", "pt": "Plano de imagem", "ar": "خطة الصورة", "bn": "ইমেজ প্ল্যান", "id": "Rencana gambar", "ur": "امیج پلان"},
    "Camera": {"fr": "Caméra", "es": "Cámara", "ja": "カメラ", "zh-Hans": "相机", "hi": "कैमरा", "ru": "Камера", "pt": "Câmera", "ar": "الكاميرا", "bn": "ক্যামেরা", "id": "Kamera", "ur": "کیمرہ"},
    "Lighting": {"fr": "Éclairage", "es": "Iluminación", "ja": "照明", "zh-Hans": "灯光", "hi": "लाइटिंग", "ru": "Свет", "pt": "Iluminação", "ar": "الإضاءة", "bn": "আলো", "id": "Pencahayaan", "ur": "لائٹنگ"},
    "Hosted API Usage": {"fr": "Usage API hébergée", "es": "Uso de API alojada", "ja": "ホストAPIの利用", "zh-Hans": "托管 API 用量", "hi": "होस्टेड API उपयोग", "ru": "Использование облачного API", "pt": "Uso de API hospedada", "ar": "استخدام واجهة API المستضافة", "bn": "হোস্টেড API ব্যবহার", "id": "Penggunaan API hosted", "ur": "ہوسٹڈ API استعمال"},
    "Continuity": {"fr": "Continuité", "es": "Continuidad", "ja": "コンティニュइティ", "zh-Hans": "连贯性", "hi": "निरंतरता", "ru": "Непрерывность", "pt": "Continuidade", "ar": "الاستمرارية", "bn": "কন্টিনিউইটি", "id": "Kontinuitas", "ur": " تسلسل"},
    "Prompt Intelligence": {"fr": "Intelligence de prompt", "es": "Inteligencia de prompt", "ja": "プロンプトインテリジェンス", "zh-Hans": "提示智能", "hi": "प्रॉम्प्ट इंटेलिजेंस", "ru": "Интеллект промпта", "pt": "Inteligência de prompt", "ar": "ذكاء الأمر", "bn": "প্রম্পট ইন্টেলিজেন্স", "id": "Prompt Intelligence", "ur": "پرامپٹ انٹیلی جنس"},
    "Add Reference": {"fr": "Ajouter une référence", "es": "Añadir referencia", "ja": "参照を追加", "zh-Hans": "添加参考", "hi": "संदर्भ जोड़ें", "ru": "Добавить ссылку", "pt": "Adicionar referência", "ar": "إضافة مرجع", "bn": "রেফারেন্স যোগ", "id": "Tambah referensi", "ur": "حوالہ شامل کریں"},
    "Upload Image to Library": {"fr": "Téléverser une image dans la bibliothèque", "es": "Subir imagen a la biblioteca", "ja": "ライブラリに画像をアップロード", "zh-Hans": "上传图像到资料库", "hi": "लाइब्रेरी में छवि अपलोड करें", "ru": "Загрузить изображение в библиотеку", "pt": "Enviar imagem para a biblioteca", "ar": "رفع صورة إلى المكتبة", "bn": "লাইব্রেরিতে ছবি আপলোড", "id": "Unggah gambar ke pustaka", "ur": "لائبریری میں تصویر اپ لوڈ کریں"},
    "Generate Images": {"fr": "Générer des images", "es": "Generar imágenes", "ja": "画像を生成", "zh-Hans": "生成图像", "hi": "छवियाँ जनरेट करें", "ru": "Создать изображения", "pt": "Gerar imagens", "ar": "إنشاء صور", "bn": "ছবি তৈরি করুন", "id": "Hasilkan gambar", "ur": "تصاویر تیار کریں"},
    "Generating…": {"fr": "Génération…", "es": "Generando…", "ja": "生成中…", "zh-Hans": "正在生成…", "hi": "जनरेट हो रहा है…", "ru": "Создание…", "pt": "Gerando…", "ar": "جارٍ الإنشاء…", "bn": "তৈরি হচ্ছে…", "id": "Menghasilkan…", "ur": "تیار ہو رہا ہے…"},
    "Open Storyboard": {"fr": "Ouvrir le storyboard", "es": "Abrir storyboard", "ja": "ストーリーボードを開く", "zh-Hans": "打开分镜", "hi": "स्टोरीबोर्ड खोलें", "ru": "Открыть раскадровку", "pt": "Abrir storyboard", "ar": "فتح لوحة القصة", "bn": "স্টোরিবোর্ড খুলুন", "id": "Buka storyboard", "ur": "اسٹوری بورڈ کھولیں"},
    "Category": {"fr": "Catégorie", "es": "Categoría", "ja": "カテゴリ", "zh-Hans": "类别", "hi": "श्रेणी", "ru": "Категория", "pt": "Categoria", "ar": "الفئة", "bn": "বিভাগ", "id": "Kategori", "ur": "زمرہ"},
    "Quality": {"fr": "Qualité", "es": "Calidad", "ja": "品質", "zh-Hans": "质量", "hi": "गुणवत्ता", "ru": "Качество", "pt": "Qualidade", "ar": "الجودة", "bn": "মান", "id": "Kualitas", "ur": "معیار"},
    "Cinematic Color Grade": {"fr": "Étalonnage cinématographique", "es": "Corrección de color cinematográfica", "ja": "シネマティックカラーグレード", "zh-Hans": "电影调色", "hi": "सिनेमैटिक कलर ग्रेड", "ru": "Кинематографический цветокор", "pt": "Cor cinematográfica", "ar": "تدرج لوني سينمائي", "bn": "সিনেমাটিক কালার গ্রেড", "id": "Grade warna sinematik", "ur": "سینمائی کلر گریڈ"},
    "Storyboard Studio": {"fr": "Studio storyboard", "es": "Estudio de storyboard", "ja": "ストーリーボードスタジオ", "zh-Hans": "分镜工作室", "hi": "स्टोरीबोर्ड स्टूडियो", "ru": "Студия раскадровки", "pt": "Estúdio de storyboard", "ar": "استوديو لوحة القصة", "bn": "স্টোরিবোর্ড স্টুডিও", "id": "Studio Storyboard", "ur": "اسٹوری بورڈ اسٹوڈیو"},
    "Generate Missing Panels": {"fr": "Générer les cases manquantes", "es": "Generar paneles faltantes", "ja": "不足パネルを生成", "zh-Hans": "生成缺失画格", "hi": "गायब पैनल जनरेट करें", "ru": "Создать недостающие кадры", "pt": "Gerar painéis ausentes", "ar": "إنشاء اللوحات الناقصة", "bn": "অনুপস্থিত প্যানেল তৈরি", "id": "Hasilkan panel yang hilang", "ur": "غائب پینل تیار کریں"},
    "Generate 2K Storyboard": {"fr": "Générer le storyboard 2K", "es": "Generar storyboard 2K", "ja": "2Kストーリーボードを生成", "zh-Hans": "生成 2K 分镜", "hi": "2K स्टोरीबोर्ड जनरेट करें", "ru": "Создать раскадровку 2K", "pt": "Gerar storyboard 2K", "ar": "إنشاء لوحة قصة 2K", "bn": "২কে স্টোরিবোর্ড তৈরি", "id": "Hasilkan storyboard 2K", "ur": "2K اسٹوری بورڈ بنائیں"},
    "Export PDF": {"fr": "Exporter PDF", "es": "Exportar PDF", "ja": "PDFを書き出す", "zh-Hans": "导出 PDF", "hi": "PDF निर्यात", "ru": "Экспорт PDF", "pt": "Exportar PDF", "ar": "تصدير PDF", "bn": "PDF রপ্তানি", "id": "Ekspor PDF", "ur": "PDF برآمد"},
    "Export JSON": {"fr": "Exporter JSON", "es": "Exportar JSON", "ja": "JSONを書き出す", "zh-Hans": "导出 JSON", "hi": "JSON निर्यात", "ru": "Экспорт JSON", "pt": "Exportar JSON", "ar": "تصدير JSON", "bn": "JSON রপ্তানি", "id": "Ekspor JSON", "ur": "JSON برآمد"},
    "Contact Sheet": {"fr": "Planche contact", "es": "Hoja de contactos", "ja": "コンタクトシート", "zh-Hans": "联系表", "hi": "संपर्क शीट", "ru": "Контакт-лист", "pt": "Folha de contato", "ar": "ورقة اتصال", "bn": "কন্টাক্ট শিট", "id": "Lembar kontak", "ur": "کنٹیکٹ شیٹ"},
    "Prepare for Timeline": {"fr": "Préparer pour la timeline", "es": "Preparar para la timeline", "ja": "タイムライン用に準備", "zh-Hans": "准备到时间线", "hi": "टाइमलाइन के लिए तैयार करें", "ru": "Подготовить к таймлайну", "pt": "Preparar para a timeline", "ar": "تجهيز للخط الزمني", "bn": "টাইমলাইনের জন্য প্রস্তুত", "id": "Siapkan untuk timeline", "ur": "ٹائم لائن کے لیے تیار کریں"},
    "Captions": {"fr": "Légendes", "es": "Pies de foto", "ja": "キャプション", "zh-Hans": "说明文字", "hi": "कैप्शन", "ru": "Подписи", "pt": "Legendas", "ar": "التعليقات", "bn": "ক্যাপশন", "id": "Keterangan", "ur": "کیپشن"},
    "Page": {"fr": "Page", "es": "Página", "ja": "ページ", "zh-Hans": "页", "hi": "पृष्ठ", "ru": "Страница", "pt": "Página", "ar": "صفحة", "bn": "পৃষ্ঠা", "id": "Halaman", "ur": "صفحہ"},
    "Previous page": {"fr": "Page précédente", "es": "Página anterior", "ja": "前のページ", "zh-Hans": "上一页", "hi": "पिछला पृष्ठ", "ru": "Предыдущая страница", "pt": "Página anterior", "ar": "الصفحة السابقة", "bn": "আগের পৃষ্ঠা", "id": "Halaman sebelumnya", "ur": "پچھلا صفحہ"},
    "Next page": {"fr": "Page suivante", "es": "Página siguiente", "ja": "次のページ", "zh-Hans": "下一页", "hi": "अगला पृष्ठ", "ru": "Следующая страница", "pt": "Próxima página", "ar": "الصفحة التالية", "bn": "পরের পৃষ্ঠা", "id": "Halaman berikutnya", "ur": "اگلا صفحہ"},
    "Character Creator": {"fr": "Créateur de personnages", "es": "Creador de personajes", "ja": "キャラクタークリエイター", "zh-Hans": "角色创作", "hi": "कैरेक्टर क्रिएटर", "ru": "Создание персонажей", "pt": "Criador de personagens", "ar": "منشئ الشخصيات", "bn": "ক্যারেক্টার ক্রিয়েটর", "id": "Pembuat Karakter", "ur": "کردار تخلیق کار"},
    "Looks": {"fr": "Looks", "es": "Looks", "ja": "ルック", "zh-Hans": "外观候选", "hi": "लुक्स", "ru": "Варианты", "pt": "Looks", "ar": "المظاهر", "bn": "লুক", "id": "Tampilan", "ur": "لُکس"},
    "Approve": {"fr": "Approuver", "es": "Aprobar", "ja": "承認", "zh-Hans": "批准", "hi": "स्वीकृत करें", "ru": "Одобрить", "pt": "Aprovar", "ar": "اعتماد", "bn": "অনুমোদন", "id": "Setujui", "ur": "منظور کریں"},
    "Character Sheet": {"fr": "Fiche personnage", "es": "Hoja de personaje", "ja": "キャラクターシート", "zh-Hans": "角色表", "hi": "कैरेक्टर शीट", "ru": "Лист персонажа", "pt": "Folha de personagem", "ar": "ورقة الشخصية", "bn": "ক্যারেক্টার শিট", "id": "Lembar karakter", "ur": "کردار شیٹ"},
    "Profile Guided": {"fr": "Guidé par le profil", "es": "Guiado por perfil", "ja": "プロファイルガイド", "zh-Hans": "档案引导", "hi": "प्रोफ़ाइल गाइडेड", "ru": "По профилю", "pt": "Guiado por perfil", "ar": "موجَّه بالملف", "bn": "প্রোফাইল গাইডেড", "id": "Dipandu profil", "ur": "پروفائل گائیڈڈ"},
    "Prop Creator": {"fr": "Créateur d’accessoires", "es": "Creador de props", "ja": "プロップクリエイター", "zh-Hans": "道具创作", "hi": "प्रॉप क्रिएटर", "ru": "Создание реквизита", "pt": "Criador de props", "ar": "منشئ الإكسسوارات", "bn": "প্রপ ক্রিয়েটর", "id": "Pembuat Properti", "ur": "پروپ تخلیق کار"},
    "Spatial Map": {"fr": "Carte spatiale", "es": "Mapa espacial", "ja": "空間マップ", "zh-Hans": "空间地图", "hi": "स्पेशियल मैप", "ru": "Пространственная карта", "pt": "Mapa espacial", "ar": "الخريطة المكانية", "bn": "স্পেশিয়াল ম্যাপ", "id": "Peta spasial", "ur": "اسپیشل نقشہ"},
    "Continue": {"fr": "Continuer", "es": "Continuar", "ja": "続ける", "zh-Hans": "继续", "hi": "जारी रखें", "ru": "Продолжить", "pt": "Continuar", "ar": "متابعة", "bn": "চালিয়ে যান", "id": "Lanjutkan", "ur": "جاری رکھیں"},
    "Place": {"fr": "Placer", "es": "Colocar", "ja": "配置", "zh-Hans": "放置", "hi": "रखें", "ru": "Разместить", "pt": "Colocar", "ar": "وضع", "bn": "রাখুন", "id": "Tempatkan", "ur": "رکھیں"},
    "Environment Reference Sheet": {"fr": "Feuille de référence d’environnement", "es": "Hoja de referencia de entorno", "ja": "環境リファレンスシート", "zh-Hans": "环境参考表", "hi": "एनवायरनमेंट संदर्भ शीट", "ru": "Лист окружения", "pt": "Folha de referência de ambiente", "ar": "ورقة مرجع البيئة", "bn": "এনভায়রনমেন্ট রেফারেন্স শিট", "id": "Lembar referensi lingkungan", "ur": "ماحول حوالہ شیٹ"},
    "Generate environment views": {"fr": "Générer les vues d’environnement", "es": "Generar vistas de entorno", "ja": "環境ビューを生成", "zh-Hans": "生成环境视图", "hi": "एनवायरनमेंट व्यू जनरेट करें", "ru": "Создать виды окружения", "pt": "Gerar vistas do ambiente", "ar": "إنشاء مشاهد البيئة", "bn": "এনভায়রনমেন্ট ভিউ তৈরি", "id": "Hasilkan tampilan lingkungan", "ur": "ماحول کے مناظر بنائیں"},
    "Select All": {"fr": "Tout sélectionner", "es": "Seleccionar todo", "ja": "すべて選択", "zh-Hans": "全选", "hi": "सभी चुनें", "ru": "Выбрать всё", "pt": "Selecionar tudo", "ar": "تحديد الكل", "bn": "সব নির্বাচন", "id": "Pilih semua", "ur": "سب منتخب کریں"},
    "Clear Selection": {"fr": "Effacer la sélection", "es": "Borrar selección", "ja": "選択を解除", "zh-Hans": "清除选择", "hi": "चयन साफ़ करें", "ru": "Снять выделение", "pt": "Limpar seleção", "ar": "مسح التحديد", "bn": "নির্বাচন মুছুন", "id": "Hapus pilihan", "ur": "انتخاب صاف کریں"},
    "Move to Folder": {"fr": "Déplacer vers un dossier", "es": "Mover a carpeta", "ja": "フォルダへ移動", "zh-Hans": "移动到文件夹", "hi": "फ़ोल्डर में ले जाएँ", "ru": "Переместить в папку", "pt": "Mover para pasta", "ar": "نقل إلى مجلد", "bn": "ফোল্ডারে সরান", "id": "Pindah ke folder", "ur": "فولڈر میں منتقل"},
    "New Folder": {"fr": "Nouveau dossier", "es": "Nueva carpeta", "ja": "新しいフォルダ", "zh-Hans": "新建文件夹", "hi": "नया फ़ोल्डर", "ru": "Новая папка", "pt": "Nova pasta", "ar": "مجلد جديد", "bn": "নতুন ফোল্ডার", "id": "Folder baru", "ur": "نیا فولڈر"},
    "Delete Folder": {"fr": "Supprimer le dossier", "es": "Eliminar carpeta", "ja": "フォルダを削除", "zh-Hans": "删除文件夹", "hi": "फ़ोल्डर हटाएँ", "ru": "Удалить папку", "pt": "Excluir pasta", "ar": "حذف المجلد", "bn": "ফোল্ডার মুছুন", "id": "Hapus folder", "ur": "فولڈر حذف کریں"},
    "Unfiled": {"fr": "Non classé", "es": "Sin carpeta", "ja": "未整理", "zh-Hans": "未归档", "hi": "बिना फ़ाइल", "ru": "Без папки", "pt": "Sem pasta", "ar": "غير مصنف", "bn": "আনফাইলড", "id": "Belum berkas", "ur": "غیر فائل شدہ"},
    "Search assets…": {"fr": "Rechercher des fichiers…", "es": "Buscar archivos…", "ja": "素材を検索…", "zh-Hans": "搜索素材…", "hi": "एसेट खोजें…", "ru": "Поиск ресурсов…", "pt": "Pesquisar arquivos…", "ar": "البحث عن الأصول…", "bn": "অ্যাসেট খুঁজুন…", "id": "Cari aset…", "ur": "اثاثے تلاش کریں…"},
    "Search library assets": {"fr": "Rechercher dans la bibliothèque", "es": "Buscar archivos de la biblioteca", "ja": "ライブラリ素材を検索", "zh-Hans": "搜索资料库素材", "hi": "लाइब्रेरी एसेट खोजें", "ru": "Поиск в библиотеке", "pt": "Pesquisar arquivos da biblioteca", "ar": "البحث في أصول المكتبة", "bn": "লাইব্রেরি অ্যাসেট খুঁজুন", "id": "Cari aset pustaka", "ur": "لائبریری اثاثے تلاش کریں"},
    "Delete {{count}} asset?": {"fr": "Supprimer {{count}} fichier ?", "es": "¿Eliminar {{count}} archivo?", "ja": "{{count}} 件の素材を削除しますか？", "zh-Hans": "删除 {{count}} 个素材？", "hi": "{{count}} एसेट हटाएँ?", "ru": "Удалить {{count}} ресурс?", "pt": "Excluir {{count}} arquivo?", "ar": "هل تريد حذف أصل {{count}}؟", "bn": "{{count}} অ্যাসেট মুছবেন?", "id": "Hapus {{count}} aset?", "ur": "{{count}} اثاثہ حذف کریں؟"},
    "Delete {{count}} assets?": {"fr": "Supprimer {{count}} fichiers ?", "es": "¿Eliminar {{count}} archivos?", "ja": "{{count}} 件の素材を削除しますか？", "zh-Hans": "删除 {{count}} 个素材？", "hi": "{{count}} एसेट हटाएँ?", "ru": "Удалить {{count}} ресурсов?", "pt": "Excluir {{count}} arquivos?", "ar": "هل تريد حذف {{count}} أصول؟", "bn": "{{count}} অ্যাসেট মুছবেন?", "id": "Hapus {{count}} aset?", "ur": "{{count}} اثاثے حذف کریں؟"},
    "Delete {{count}} Assets": {"fr": "Supprimer {{count}} fichiers", "es": "Eliminar {{count}} archivos", "ja": "{{count}} 件を削除", "zh-Hans": "删除 {{count}} 个素材", "hi": "{{count}} एसेट हटाएँ", "ru": "Удалить {{count}}", "pt": "Excluir {{count}} arquivos", "ar": "حذف {{count}} أصول", "bn": "{{count}} অ্যাসেট মুছুন", "id": "Hapus {{count}} aset", "ur": "{{count}} اثاثے حذف کریں"},
    "Untitled": {"fr": "Sans titre", "es": "Sin título", "ja": "無題", "zh-Hans": "未命名", "hi": "शीर्षकहीन", "ru": "Без названия", "pt": "Sem título", "ar": "بدون عنوان", "bn": "শিরোনামহীন", "id": "Tanpa judul", "ur": "بلا عنوان"},
    "Scriptwriter": {"fr": "Scénariste", "es": "Guionista", "ja": "脚本", "zh-Hans": "编剧", "hi": "स्क्रिप्टराइटर", "ru": "Сценарист", "pt": "Roteirista", "ar": "كاتب السيناريو", "bn": "স্ক্রিপ্টরাইটার", "id": "Penulis naskah", "ur": "اسکرپٹ رائٹر"},
    "New scene": {"fr": "Nouvelle scène", "es": "Nueva escena", "ja": "新しいシーン", "zh-Hans": "新建场景", "hi": "नया सीन", "ru": "Новая сцена", "pt": "Nova cena", "ar": "مشهد جديد", "bn": "নতুন দৃশ্য", "id": "Adegan baru", "ur": "نیا سین"},
    "MAGI Editor": {"fr": "Éditeur MAGI", "es": "Editor MAGI", "ja": "MAGIエディター", "zh-Hans": "MAGI 编辑器", "hi": "MAGI संपादक", "ru": "Редактор MAGI", "pt": "Editor MAGI", "ar": "محرر MAGI", "bn": "MAGI এডিটর", "id": "Editor MAGI", "ur": "MAGI ایڈیٹر"},
    "Cut": {"fr": "Couper", "es": "Cortar", "ja": "カット", "zh-Hans": "剪切", "hi": "काटें", "ru": "Вырезать", "pt": "Cortar", "ar": "قص", "bn": "কাট", "id": "Potong", "ur": "کاٹیں"},
    "Something went wrong.": {"fr": "Une erreur s’est produite.", "es": "Algo salió mal.", "ja": "問題が発生しました。", "zh-Hans": "出了点问题。", "hi": "कुछ गलत हो गया।", "ru": "Что-то пошло не так.", "pt": "Algo deu errado.", "ar": "حدث خطأ ما.", "bn": "কিছু ভুল হয়েছে।", "id": "Terjadi kesalahan.", "ur": "کچھ غلط ہو گیا۔"},
    "Network error. Check your connection.": {"fr": "Erreur réseau. Vérifiez votre connexion.", "es": "Error de red. Comprueba tu conexión.", "ja": "ネットワークエラー。接続を確認してください。", "zh-Hans": "网络错误。请检查连接。", "hi": "नेटवर्क त्रुटि। कनेक्शन जाँचें।", "ru": "Ошибка сети. Проверьте подключение.", "pt": "Erro de rede. Verifique a conexão.", "ar": "خطأ في الشبكة. تحقق من الاتصال.", "bn": "নেটওয়ার্ক ত্রুটি। সংযোগ পরীক্ষা করুন।", "id": "Kesalahan jaringan. Periksa koneksi.", "ur": "نیٹ ورک خرابی۔ کنکشن چیک کریں۔"},
    "Not found.": {"fr": "Introuvable.", "es": "No encontrado.", "ja": "見つかりません。", "zh-Hans": "未找到。", "hi": "नहीं मिला।", "ru": "Не найдено.", "pt": "Não encontrado.", "ar": "غير موجود.", "bn": "পাওয়া যায়নি।", "id": "Tidak ditemukan.", "ur": "نہیں ملا۔"},
    "Not authorized.": {"fr": "Non autorisé.", "es": "No autorizado.", "ja": "権限がありません。", "zh-Hans": "未授权。", "hi": "अधिकृत नहीं।", "ru": "Нет доступа.", "pt": "Não autorizado.", "ar": "غير مصرح.", "bn": "অননুমোদিত।", "id": "Tidak diizinkan.", "ur": "اختیار نہیں۔"},
    "Validation failed.": {"fr": "Échec de la validation.", "es": "Error de validación.", "ja": "検証に失敗しました。", "zh-Hans": "验证失败。", "hi": "सत्यापन विफल।", "ru": "Ошибка проверки.", "pt": "Falha na validação.", "ar": "فشل التحقق.", "bn": "যাচাই ব্যর্থ।", "id": "Validasi gagal.", "ur": "توثیق ناکام۔"},
    "Enter a creator prompt first.": {"fr": "Saisissez d’abord un prompt créateur.", "es": "Escribe primero un prompt de creador.", "ja": "まずクリエイターのプロンプトを入力してください。", "zh-Hans": "请先输入创作者提示。", "hi": "पहले क्रिएटर प्रॉम्प्ट लिखें।", "ru": "Сначала введите промпт.", "pt": "Digite primeiro um prompt do criador.", "ar": "أدخل أمر المبدع أولاً.", "bn": "আগে একটি ক্রিয়েটর প্রম্পট লিখুন।", "id": "Masukkan prompt kreator dulu.", "ur": "پہلے تخلیق کار پرامپٹ لکھیں۔"},
    "That file type cannot be used on this track.": {"fr": "Ce type de fichier ne peut pas être utilisé sur cette piste.", "es": "Ese tipo de archivo no se puede usar en esta pista.", "ja": "このトラックではそのファイル種類は使えません。", "zh-Hans": "该文件类型不能用于此轨道。", "hi": "यह फ़ाइल प्रकार इस ट्रैक पर नहीं चल सकता।", "ru": "Этот тип файла нельзя использовать на этой дорожке.", "pt": "Esse tipo de arquivo não pode ser usado nesta faixa.", "ar": "لا يمكن استخدام هذا النوع من الملفات على هذا المسار.", "bn": "এই ফাইলের ধরন এই ট্র্যাকে ব্যবহার করা যাবে না।", "id": "Jenis file itu tidak bisa dipakai di trek ini.", "ur": "یہ فائل قسم اس ٹریک پر استعمال نہیں ہو سکتی۔"},
    "Technical detail": {"fr": "Détail technique", "es": "Detalle técnico", "ja": "技術詳細", "zh-Hans": "技术细节", "hi": "तकनीकी विवरण", "ru": "Техническая деталь", "pt": "Detalhe técnico", "ar": "تفاصيل تقنية", "bn": "প্রযুক্তিগত বিবরণ", "id": "Detail teknis", "ur": "تکنیکی تفصیل"},
    "What is {{lens}}?": {"fr": "Qu’est-ce que {{lens}} ?", "es": "¿Qué es {{lens}}?", "ja": "{{lens}} とは？", "zh-Hans": "{{lens}} 是什么？", "hi": "{{lens}} क्या है?", "ru": "Что такое {{lens}}?", "pt": "O que é {{lens}}?", "ar": "ما هو {{lens}}؟", "bn": "{{lens}} কী?", "id": "Apa itu {{lens}}?", "ur": "{{lens}} کیا ہے؟"},
    "{{seconds}} sec": {"fr": "{{seconds}} s", "es": "{{seconds}} s", "ja": "{{seconds}} 秒", "zh-Hans": "{{seconds}} 秒", "hi": "{{seconds}} सेकंड", "ru": "{{seconds}} с", "pt": "{{seconds}} s", "ar": "{{seconds}} ث", "bn": "{{seconds}} সেকেন্ড", "id": "{{seconds}} dtk", "ur": "{{seconds}} سیکنڈ"},
    "Project": {"fr": "Projet", "es": "Proyecto", "ja": "プロジェクト", "zh-Hans": "项目", "hi": "प्रोजेक्ट", "ru": "Проект", "pt": "Projeto", "ar": "المشروع", "bn": "প্রকল্প", "id": "Proyek", "ur": "پروجیکٹ"},
    "Global": {"fr": "Global", "es": "Global", "ja": "グローバル", "zh-Hans": "全局", "hi": "ग्लोबल", "ru": "Глобально", "pt": "Global", "ar": "عام", "bn": "গ্লোবাল", "id": "Global", "ur": "عالمی"},
    "Generate Prop Images": {"fr": "Générer des images d’accessoire", "es": "Generar imágenes del prop", "ja": "プロップ画像を生成", "zh-Hans": "生成道具图像", "hi": "प्रॉप छवियाँ जनरेट करें", "ru": "Создать изображения реквизита", "pt": "Gerar imagens do prop", "ar": "إنشاء صور الإكسسوار", "bn": "প্রপ ছবি তৈরি করুন", "id": "Hasilkan gambar prop", "ur": "پروپ تصاویر تیار کریں"},
    "Generating…": {"fr": "Génération…", "es": "Generando…", "ja": "生成中…", "zh-Hans": "生成中…", "hi": "जनरेट हो रहा है…", "ru": "Создание…", "pt": "Gerando…", "ar": "جارٍ الإنشاء…", "bn": "তৈরি হচ্ছে…", "id": "Menghasilkan…", "ur": "تیار ہو رہا ہے…"},
    "Loading Prop Creator…": {"fr": "Chargement du créateur d’accessoires…", "es": "Cargando Creador de props…", "ja": "プロップクリエイターを読み込み中…", "zh-Hans": "正在加载道具创建器…", "hi": "प्रॉप क्रिएटर लोड हो रहा है…", "ru": "Загрузка создателя реквизита…", "pt": "Carregando criador de props…", "ar": "جارٍ تحميل منشئ الإكسسوارات…", "bn": "প্রপ ক্রিয়েটর লোড হচ্ছে…", "id": "Memuat pembuat prop…", "ur": "پروپ تخلیق کار لوڈ ہو رہا ہے…"},
    "Loading Spatial Map…": {"fr": "Chargement de la carte spatiale…", "es": "Cargando mapa espacial…", "ja": "空間マップを読み込み中…", "zh-Hans": "正在加载空间地图…", "hi": "स्पेशियल मैप लोड हो रहा है…", "ru": "Загрузка пространственной карты…", "pt": "Carregando mapa espacial…", "ar": "جارٍ تحميل الخريطة المكانية…", "bn": "স্পেশিয়াল ম্যাপ লোড হচ্ছে…", "id": "Memuat peta spasial…", "ur": "اسپیشل میپ لوڈ ہو رہا ہے…"},
    "Scriptwriter Studio": {"fr": "Studio scénariste", "es": "Estudio de guionista", "ja": "脚本スタジオ", "zh-Hans": "编剧工作室", "hi": "स्क्रिप्टराइटर स्टूडियो", "ru": "Студия сценариста", "pt": "Estúdio de roteiro", "ar": "استوديو كتابة السيناريو", "bn": "স্ক্রিপ্টরাইটার স্টুডিও", "id": "Studio penulis naskah", "ur": "اسکرپٹ رائٹر اسٹوڈیو"},
    "Playing": {"fr": "Lecture", "es": "Reproduciendo", "ja": "再生中", "zh-Hans": "播放中", "hi": "चल रहा है", "ru": "Воспроизведение", "pt": "Reproduzindo", "ar": "قيد التشغيل", "bn": "চালু আছে", "id": "Memutar", "ur": "چل رہا ہے"},
    "Paused": {"fr": "En pause", "es": "En pausa", "ja": "一時停止", "zh-Hans": "已暂停", "hi": "विराम", "ru": "Пауза", "pt": "Pausado", "ar": "متوقف مؤقتًا", "bn": "বিরতি", "id": "Dijeda", "ur": "وقفہ"},
}


def translate(en_text: str, locale: str) -> str:
    row = PHRASES.get(en_text)
    if row and locale in row:
        return row[locale]
    return en_text


def main() -> None:
    en_dir = LOCALES_DIR / "en"
    filled = 0
    copied = 0
    for ns_path in sorted(en_dir.glob("*.json")):
        en = json.loads(ns_path.read_text(encoding="utf-8"))
        for locale in LOCALES:
            dest = LOCALES_DIR / locale / ns_path.name
            dest.parent.mkdir(parents=True, exist_ok=True)
            existing: dict[str, str] = {}
            if dest.exists():
                existing = json.loads(dest.read_text(encoding="utf-8"))
            out: dict[str, str] = dict(existing)
            for key, en_val in en.items():
                if key in out and str(out[key]).strip():
                    continue
                translated = translate(str(en_val), locale)
                out[key] = translated
                if translated == en_val:
                    copied += 1
                else:
                    filled += 1
            dest.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"filled={filled} copied_en_fallback={copied}")


if __name__ == "__main__":
    main()
