#!/usr/bin/env python3
"""Seed M3.0F i18n locales, language intelligence module, and docs stubs."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_I18N = ROOT / "studio-web" / "src" / "i18n"
API_LI = ROOT / "studio-api" / "app" / "codirector" / "language_intelligence"
DOCS = ROOT / "docs" / "release-gate" / "multilingual"

LOCALES = [
    ("en", "English", "English", "ltr", "en", "en", "ACTIVE", "HUMAN_APPROVED"),
    ("fr", "French", "Français", "ltr", "fr", "fr", "ACTIVE", "MACHINE_DRAFT"),
    ("es", "Spanish", "Español", "ltr", "es", "es", "ACTIVE", "MACHINE_DRAFT"),
    ("ja", "Japanese", "日本語", "ltr", "ja", "ja", "ACTIVE", "MACHINE_DRAFT"),
    ("zh-Hans", "Chinese (Simplified)", "简体中文", "ltr", "zh-CN", "zh-CN", "ACTIVE", "MACHINE_DRAFT"),
    ("hi", "Hindi", "हिन्दी", "ltr", "hi", "hi", "ACTIVE", "MACHINE_DRAFT"),
    ("ru", "Russian", "Русский", "ltr", "ru", "ru", "ACTIVE", "MACHINE_DRAFT"),
    ("pt", "Portuguese", "Português", "ltr", "pt-BR", "pt-BR", "ACTIVE", "MACHINE_DRAFT"),
    ("ar", "Arabic", "العربية", "rtl", "ar", "ar", "ACTIVE", "MACHINE_DRAFT"),
    ("bn", "Bengali", "বাংলা", "ltr", "bn", "bn", "ACTIVE", "MACHINE_DRAFT"),
    ("id", "Indonesian", "Bahasa Indonesia", "ltr", "id", "id", "ACTIVE", "MACHINE_DRAFT"),
    ("ur", "Urdu", "اردو", "rtl", "ur", "ur", "ACTIVE", "MACHINE_DRAFT"),
]

NAMESPACES = [
    "common",
    "navigation",
    "projects",
    "codirector",
    "production-bible",
    "director",
    "editor",
    "approval",
    "jobs",
    "providers",
    "models",
    "settings",
    "errors",
    "accessibility",
    "export",
    "onboarding",
    "help",
]

# English source of truth (beta-critical keys)
EN: dict[str, dict[str, str]] = {
    "common": {
        "appName": "Adept UI",
        "save": "Save",
        "cancel": "Cancel",
        "close": "Close",
        "confirm": "Confirm",
        "delete": "Delete",
        "edit": "Edit",
        "loading": "Loading…",
        "retry": "Retry",
        "back": "Back",
        "next": "Next",
        "search": "Search",
        "language": "Language",
        "settings": "Settings",
        "yes": "Yes",
        "no": "No",
        "unknown": "Unknown",
        "copy": "Copy",
        "export": "Export",
        "import": "Import",
        "refresh": "Refresh",
    },
    "navigation": {
        "home": "Home",
        "projectHome": "Project Home",
        "setup": "Setup",
        "settings": "Settings",
        "director": "Director",
        "editor": "Editor",
        "bible": "Production Bible",
        "jobs": "Jobs",
        "library": "Library",
        "coDirector": "Co-Director",
        "generate": "Generate",
        "audioStudio": "Audio Studio",
        "imagegen": "ImageGen",
        "txt2vid": "Txt2Vid",
        "profiles": "Profiles",
        "script": "Script / Storyboard",
        "shotlist": "Shot List",
        "mastersheet": "Scene Master Sheet",
        "marketplace": "Marketplace",
        "avatar": "Avatar Studio",
        "sourceManager": "Source Manager",
        "modelRadar": "Model Radar",
        "virtualStage": "Virtual Stage",
        "environmentStudio": "Environment Studio",
        "productionSuite": "Production Suite",
    },
    "projects": {
        "title": "Projects",
        "newProject": "New project",
        "openProject": "Open project",
        "recentProjects": "Recent projects",
        "projectName": "Project name",
        "create": "Create project",
        "empty": "No projects yet.",
        "canonicalLanguage": "Project canonical language",
        "primaryLanguage": "Project primary language",
    },
    "codirector": {
        "title": "Co-Director",
        "placeholder": "Describe your creative intent…",
        "send": "Send",
        "conversationLanguage": "Conversation language",
        "recommendedModel": "Recommended model",
        "why": "Why",
        "confidence": "Confidence",
        "audioPlan": "Audio plan",
        "knownLimitation": "Known limitation",
        "advanced": "Advanced",
        "compiledPrompt": "Compiled prompt",
        "appliedRules": "Applied rules",
        "alternatives": "Alternatives",
        "thinking": "Thinking…",
        "meeting": "Meeting",
        "plan": "Plan",
        "explain": "Explain",
    },
    "production-bible": {
        "title": "Production Bible",
        "entities": "Entities",
        "facts": "Facts",
        "canon": "Canon",
        "proposals": "Proposals",
        "approve": "Approve",
        "reject": "Reject",
        "requestRevision": "Request revision",
        "localizedDisplay": "Localized display",
        "canonicalText": "Canonical text",
        "translationStatus": "Translation status",
        "glossary": "Glossary",
        "protectedTerm": "Protected term",
    },
    "director": {
        "title": "Director",
        "timeline": "Timeline",
        "tracks": "Tracks",
        "play": "Play",
        "pause": "Pause",
        "stop": "Stop",
        "addCue": "Add cue",
        "scene": "Scene",
        "shot": "Shot",
    },
    "editor": {
        "title": "Editor",
        "sequence": "Sequence",
        "cut": "Cut",
        "trim": "Trim",
        "exportEdit": "Export edit",
        "emptyTimeline": "Timeline is empty.",
    },
    "approval": {
        "title": "Approval Center",
        "pending": "Pending",
        "approved": "Approved",
        "rejected": "Rejected",
        "overrideReason": "Override reason",
        "requiresReason": "An override reason is required.",
    },
    "jobs": {
        "title": "Jobs",
        "queued": "Queued",
        "running": "Running",
        "succeeded": "Succeeded",
        "failed": "Job {{jobName}} failed",
        "cancelled": "Cancelled",
        "recover": "Recover jobs",
        "inspect": "Inspect job",
        "noJobs": "No jobs yet.",
        "status": "Status",
    },
    "providers": {
        "title": "Providers",
        "local": "Local",
        "fal": "fal.ai",
        "unavailable": "Provider unavailable",
        "health": "Provider health",
    },
    "models": {
        "title": "Models",
        "select": "Select model",
        "limitations": "Limitations",
        "readiness": "Readiness",
        "promptLanguage": "Prompt language",
        "preferredPromptLanguage": "Preferred prompt language",
    },
    "settings": {
        "title": "Settings",
        "interfaceLanguage": "Interface language",
        "conversationLanguage": "Co-Director conversation language",
        "projectLanguage": "Project primary language",
        "promptLanguagePolicy": "Generation prompt language policy",
        "exportLanguage": "Export language",
        "languageHelp": "Interface language does not change project canon language.",
        "followOs": "Use system language when supported",
        "rtlNote": "Arabic and Urdu use right-to-left layout.",
        "portugueseNote": "Portuguese uses Brazilian Portuguese conventions (pt-BR).",
    },
    "errors": {
        "generic": "Something went wrong.",
        "network": "Network error. Check your connection.",
        "notFound": "Not found.",
        "unauthorized": "Not authorized.",
        "validation": "Validation failed.",
        "modelKnowledgeUnavailable": "Model knowledge is unavailable for the selected model.",
        "translationFailed": "Translation failed. Original text was preserved.",
        "languagePackInvalid": "Language pack failed validation.",
        "recoveryHint": "Try again or recover running jobs from Jobs.",
    },
    "accessibility": {
        "skipToContent": "Skip to content",
        "mainNav": "Main navigation",
        "closeDialog": "Close dialog",
        "openCoDirector": "Open Co-Director",
        "languageSelector": "Select language",
        "jobStatus": "Job status {{status}}",
        "timeline": "Director timeline",
        "playback": "Playback controls",
    },
    "export": {
        "title": "Export",
        "canonicalOnly": "Canonical language only",
        "selectedOnly": "Selected language only",
        "canonicalPlusSelected": "Canonical plus selected language",
        "allLanguages": "All available languages",
        "manifest": "Export manifest",
        "success": "Export completed.",
        "failed": "Export failed.",
    },
    "onboarding": {
        "welcome": "Welcome to Adept UI",
        "chooseLanguage": "Choose your language",
        "continue": "Continue",
        "setupHint": "You can change language later in Settings.",
    },
    "help": {
        "title": "Help",
        "docs": "Documentation",
        "keyboard": "Keyboard shortcuts",
        "aboutLanguages": "About languages",
    },
}

# Machine-draft translations for non-English locales (honest MACHINE_DRAFT).
# Keys must match EN exactly for coverage.
TR: dict[str, dict[str, dict[str, str]]] = {
    "fr": {
        "common": {
            "appName": "Adept UI",
            "save": "Enregistrer",
            "cancel": "Annuler",
            "close": "Fermer",
            "confirm": "Confirmer",
            "delete": "Supprimer",
            "edit": "Modifier",
            "loading": "Chargement…",
            "retry": "Réessayer",
            "back": "Retour",
            "next": "Suivant",
            "search": "Rechercher",
            "language": "Langue",
            "settings": "Paramètres",
            "yes": "Oui",
            "no": "Non",
            "unknown": "Inconnu",
            "copy": "Copier",
            "export": "Exporter",
            "import": "Importer",
            "refresh": "Actualiser",
        },
        "navigation": {
            "home": "Accueil",
            "projectHome": "Accueil du projet",
            "setup": "Configuration",
            "settings": "Paramètres",
            "director": "Réalisateur",
            "editor": "Éditeur",
            "bible": "Bible de production",
            "jobs": "Tâches",
            "library": "Bibliothèque",
            "coDirector": "Co-réalisateur",
            "generate": "Générer",
            "audioStudio": "Studio audio",
            "imagegen": "ImageGen",
            "txt2vid": "Txt2Vid",
            "profiles": "Profils",
            "script": "Scénario / Storyboard",
            "shotlist": "Liste des plans",
            "mastersheet": "Fiche maître de scène",
            "marketplace": "Marketplace",
            "avatar": "Studio Avatar",
            "sourceManager": "Gestionnaire de sources",
            "modelRadar": "Radar des modèles",
            "virtualStage": "Scène virtuelle",
            "environmentStudio": "Studio d'environnement",
            "productionSuite": "Suite de production",
        },
        "settings": {
            "title": "Paramètres",
            "interfaceLanguage": "Langue de l'interface",
            "conversationLanguage": "Langue de conversation du Co-réalisateur",
            "projectLanguage": "Langue principale du projet",
            "promptLanguagePolicy": "Politique de langue des prompts",
            "exportLanguage": "Langue d'export",
            "languageHelp": "La langue de l'interface ne change pas la langue canonique du projet.",
            "followOs": "Utiliser la langue du système si prise en charge",
            "rtlNote": "L'arabe et l'ourdou utilisent une mise en page de droite à gauche.",
            "portugueseNote": "Le portugais utilise les conventions brésiliennes (pt-BR).",
        },
        "errors": {
            "generic": "Une erreur s'est produite.",
            "network": "Erreur réseau. Vérifiez votre connexion.",
            "notFound": "Introuvable.",
            "unauthorized": "Non autorisé.",
            "validation": "Échec de la validation.",
            "modelKnowledgeUnavailable": "Les connaissances du modèle sont indisponibles.",
            "translationFailed": "Échec de la traduction. Le texte d'origine a été conservé.",
            "languagePackInvalid": "Le pack de langue a échoué à la validation.",
            "recoveryHint": "Réessayez ou récupérez les tâches depuis Tâches.",
        },
        "jobs": {
            "title": "Tâches",
            "queued": "En file",
            "running": "En cours",
            "succeeded": "Réussi",
            "failed": "La tâche {{jobName}} a échoué",
            "cancelled": "Annulé",
            "recover": "Récupérer les tâches",
            "inspect": "Inspecter la tâche",
            "noJobs": "Aucune tâche pour le moment.",
            "status": "Statut",
        },
        "codirector": {
            "title": "Co-réalisateur",
            "placeholder": "Décrivez votre intention créative…",
            "send": "Envoyer",
            "conversationLanguage": "Langue de conversation",
            "recommendedModel": "Modèle recommandé",
            "why": "Pourquoi",
            "confidence": "Confiance",
            "audioPlan": "Plan audio",
            "knownLimitation": "Limitation connue",
            "advanced": "Avancé",
            "compiledPrompt": "Prompt compilé",
            "appliedRules": "Règles appliquées",
            "alternatives": "Alternatives",
            "thinking": "Réflexion…",
            "meeting": "Réunion",
            "plan": "Plan",
            "explain": "Expliquer",
        },
    },
    "es": {
        "common": {
            "appName": "Adept UI",
            "save": "Guardar",
            "cancel": "Cancelar",
            "close": "Cerrar",
            "confirm": "Confirmar",
            "delete": "Eliminar",
            "edit": "Editar",
            "loading": "Cargando…",
            "retry": "Reintentar",
            "back": "Atrás",
            "next": "Siguiente",
            "search": "Buscar",
            "language": "Idioma",
            "settings": "Configuración",
            "yes": "Sí",
            "no": "No",
            "unknown": "Desconocido",
            "copy": "Copiar",
            "export": "Exportar",
            "import": "Importar",
            "refresh": "Actualizar",
        },
        "navigation": {
            "home": "Inicio",
            "projectHome": "Inicio del proyecto",
            "setup": "Configuración inicial",
            "settings": "Ajustes",
            "director": "Director",
            "editor": "Editor",
            "bible": "Biblia de producción",
            "jobs": "Trabajos",
            "library": "Biblioteca",
            "coDirector": "Co-Director",
            "generate": "Generar",
            "audioStudio": "Estudio de audio",
            "imagegen": "ImageGen",
            "txt2vid": "Txt2Vid",
            "profiles": "Perfiles",
            "script": "Guion / Storyboard",
            "shotlist": "Lista de planos",
            "mastersheet": "Hoja maestra de escena",
            "marketplace": "Marketplace",
            "avatar": "Estudio Avatar",
            "sourceManager": "Gestor de fuentes",
            "modelRadar": "Radar de modelos",
            "virtualStage": "Escenario virtual",
            "environmentStudio": "Estudio de entorno",
            "productionSuite": "Suite de producción",
        },
        "settings": {
            "title": "Ajustes",
            "interfaceLanguage": "Idioma de la interfaz",
            "conversationLanguage": "Idioma de conversación del Co-Director",
            "projectLanguage": "Idioma principal del proyecto",
            "promptLanguagePolicy": "Política de idioma de prompts",
            "exportLanguage": "Idioma de exportación",
            "languageHelp": "El idioma de la interfaz no cambia el idioma canónico del proyecto.",
            "followOs": "Usar el idioma del sistema si es compatible",
            "rtlNote": "El árabe y el urdu usan diseño de derecha a izquierda.",
            "portugueseNote": "El portugués usa convenciones brasileñas (pt-BR).",
        },
        "errors": {
            "generic": "Algo salió mal.",
            "network": "Error de red. Compruebe su conexión.",
            "notFound": "No encontrado.",
            "unauthorized": "No autorizado.",
            "validation": "Error de validación.",
            "modelKnowledgeUnavailable": "El conocimiento del modelo no está disponible.",
            "translationFailed": "Falló la traducción. Se conservó el texto original.",
            "languagePackInvalid": "El paquete de idioma no superó la validación.",
            "recoveryHint": "Inténtelo de nuevo o recupere trabajos desde Trabajos.",
        },
        "jobs": {
            "title": "Trabajos",
            "queued": "En cola",
            "running": "En ejecución",
            "succeeded": "Correcto",
            "failed": "El trabajo {{jobName}} falló",
            "cancelled": "Cancelado",
            "recover": "Recuperar trabajos",
            "inspect": "Inspeccionar trabajo",
            "noJobs": "Aún no hay trabajos.",
            "status": "Estado",
        },
        "codirector": {
            "title": "Co-Director",
            "placeholder": "Describa su intención creativa…",
            "send": "Enviar",
            "conversationLanguage": "Idioma de conversación",
            "recommendedModel": "Modelo recomendado",
            "why": "Por qué",
            "confidence": "Confianza",
            "audioPlan": "Plan de audio",
            "knownLimitation": "Limitación conocida",
            "advanced": "Avanzado",
            "compiledPrompt": "Prompt compilado",
            "appliedRules": "Reglas aplicadas",
            "alternatives": "Alternativas",
            "thinking": "Pensando…",
            "meeting": "Reunión",
            "plan": "Plan",
            "explain": "Explicar",
        },
    },
}


def deep_fill(locale: str) -> dict[str, dict[str, str]]:
    """Fill all namespaces for a locale; fall back to EN then overlay TR."""
    out: dict[str, dict[str, str]] = {}
    for ns, keys in EN.items():
        out[ns] = dict(keys)
        if locale in TR and ns in TR[locale]:
            out[ns].update(TR[locale][ns])
    return out


# Compact machine drafts for remaining locales (critical namespaces only overlay).
COMPACT = {
    "ja": {
        "common": {"save": "保存", "cancel": "キャンセル", "close": "閉じる", "language": "言語", "settings": "設定", "loading": "読み込み中…", "search": "検索", "retry": "再試行"},
        "navigation": {"home": "ホーム", "director": "ディレクター", "editor": "エディター", "bible": "プロダクションバイブル", "jobs": "ジョブ", "coDirector": "共同監督", "settings": "設定"},
        "settings": {"title": "設定", "interfaceLanguage": "インターフェース言語", "conversationLanguage": "共同監督の会話言語", "languageHelp": "インターフェース言語はプロジェクトの正規言語を変更しません。"},
        "errors": {"generic": "問題が発生しました。", "modelKnowledgeUnavailable": "選択したモデルの知識は利用できません。", "translationFailed": "翻訳に失敗しました。原文を保持しました。"},
        "jobs": {"title": "ジョブ", "failed": "ジョブ {{jobName}} が失敗しました", "running": "実行中", "succeeded": "成功"},
        "codirector": {"title": "共同監督", "placeholder": "創作意図を記述…", "send": "送信", "recommendedModel": "推奨モデル"},
    },
    "zh-Hans": {
        "common": {"save": "保存", "cancel": "取消", "close": "关闭", "language": "语言", "settings": "设置", "loading": "加载中…", "search": "搜索", "retry": "重试"},
        "navigation": {"home": "首页", "director": "导演", "editor": "剪辑", "bible": "制片圣经", "jobs": "任务", "coDirector": "联合导演", "settings": "设置"},
        "settings": {"title": "设置", "interfaceLanguage": "界面语言", "conversationLanguage": "联合导演对话语言", "languageHelp": "界面语言不会更改项目规范语言。"},
        "errors": {"generic": "出错了。", "modelKnowledgeUnavailable": "所选模型的知识不可用。", "translationFailed": "翻译失败。已保留原文。"},
        "jobs": {"title": "任务", "failed": "任务 {{jobName}} 失败", "running": "运行中", "succeeded": "成功"},
        "codirector": {"title": "联合导演", "placeholder": "描述您的创作意图…", "send": "发送", "recommendedModel": "推荐模型"},
    },
    "hi": {
        "common": {"save": "सहेजें", "cancel": "रद्द करें", "close": "बंद करें", "language": "भाषा", "settings": "सेटिंग्स", "loading": "लोड हो रहा है…", "search": "खोजें", "retry": "पुनः प्रयास"},
        "navigation": {"home": "होम", "director": "निर्देशक", "editor": "संपादक", "bible": "प्रोडक्शन बाइबल", "jobs": "जॉब्स", "coDirector": "सह-निर्देशक", "settings": "सेटिंग्स"},
        "settings": {"title": "सेटिंग्स", "interfaceLanguage": "इंटरफ़ेस भाषा", "conversationLanguage": "सह-निर्देशक वार्तालाप भाषा", "languageHelp": "इंटरफ़ेस भाषा परियोजना की प्रामाणिक भाषा नहीं बदलती।"},
        "errors": {"generic": "कुछ गलत हो गया।", "modelKnowledgeUnavailable": "चयनित मॉडल का ज्ञान उपलब्ध नहीं है।", "translationFailed": "अनुवाद विफल। मूल पाठ सुरक्षित रखा गया।"},
        "jobs": {"title": "जॉब्स", "failed": "जॉब {{jobName}} विफल", "running": "चल रहा है", "succeeded": "सफल"},
        "codirector": {"title": "सह-निर्देशक", "placeholder": "अपना रचनात्मक आशय लिखें…", "send": "भेजें", "recommendedModel": "अनुशंसित मॉडल"},
    },
    "ru": {
        "common": {"save": "Сохранить", "cancel": "Отмена", "close": "Закрыть", "language": "Язык", "settings": "Настройки", "loading": "Загрузка…", "search": "Поиск", "retry": "Повторить"},
        "navigation": {"home": "Главная", "director": "Режиссёр", "editor": "Монтаж", "bible": "Продакшн-библия", "jobs": "Задачи", "coDirector": "Сорежиссёр", "settings": "Настройки"},
        "settings": {"title": "Настройки", "interfaceLanguage": "Язык интерфейса", "conversationLanguage": "Язык общения с сорежиссёром", "languageHelp": "Язык интерфейса не меняет канонический язык проекта."},
        "errors": {"generic": "Что-то пошло не так.", "modelKnowledgeUnavailable": "Знания о модели недоступны.", "translationFailed": "Перевод не удался. Исходный текст сохранён."},
        "jobs": {"title": "Задачи", "failed": "Задача {{jobName}} не выполнена", "running": "Выполняется", "succeeded": "Успешно"},
        "codirector": {"title": "Сорежиссёр", "placeholder": "Опишите творческий замысел…", "send": "Отправить", "recommendedModel": "Рекомендуемая модель"},
    },
    "pt": {
        "common": {"save": "Salvar", "cancel": "Cancelar", "close": "Fechar", "language": "Idioma", "settings": "Configurações", "loading": "Carregando…", "search": "Pesquisar", "retry": "Tentar de novo"},
        "navigation": {"home": "Início", "director": "Diretor", "editor": "Editor", "bible": "Bíblia de produção", "jobs": "Tarefas", "coDirector": "Co-diretor", "settings": "Configurações"},
        "settings": {"title": "Configurações", "interfaceLanguage": "Idioma da interface", "conversationLanguage": "Idioma da conversa do Co-diretor", "languageHelp": "O idioma da interface não altera o idioma canônico do projeto.", "portugueseNote": "O português usa convenções do Brasil (pt-BR)."},
        "errors": {"generic": "Algo deu errado.", "modelKnowledgeUnavailable": "O conhecimento do modelo está indisponível.", "translationFailed": "Falha na tradução. O texto original foi preservado."},
        "jobs": {"title": "Tarefas", "failed": "A tarefa {{jobName}} falhou", "running": "Em execução", "succeeded": "Concluído"},
        "codirector": {"title": "Co-diretor", "placeholder": "Descreva sua intenção criativa…", "send": "Enviar", "recommendedModel": "Modelo recomendado"},
    },
    "ar": {
        "common": {"save": "حفظ", "cancel": "إلغاء", "close": "إغلاق", "language": "اللغة", "settings": "الإعدادات", "loading": "جارٍ التحميل…", "search": "بحث", "retry": "إعادة المحاولة"},
        "navigation": {"home": "الرئيسية", "director": "المخرج", "editor": "المحرر", "bible": "كتاب الإنتاج", "jobs": "المهام", "coDirector": "المخرج المشارك", "settings": "الإعدادات"},
        "settings": {"title": "الإعدادات", "interfaceLanguage": "لغة الواجهة", "conversationLanguage": "لغة محادثة المخرج المشارك", "languageHelp": "لغة الواجهة لا تغيّر لغة المشروع الأساسية.", "rtlNote": "العربية والأردية تستخدمان تخطيطًا من اليمين إلى اليسار."},
        "errors": {"generic": "حدث خطأ ما.", "modelKnowledgeUnavailable": "معرفة النموذج غير متاحة.", "translationFailed": "فشلت الترجمة. تم الاحتفاظ بالنص الأصلي."},
        "jobs": {"title": "المهام", "failed": "فشلت المهمة {{jobName}}", "running": "قيد التشغيل", "succeeded": "نجح"},
        "codirector": {"title": "المخرج المشارك", "placeholder": "صف نيتك الإبداعية…", "send": "إرسال", "recommendedModel": "النموذج الموصى به"},
    },
    "bn": {
        "common": {"save": "সংরক্ষণ", "cancel": "বাতিল", "close": "বন্ধ", "language": "ভাষা", "settings": "সেটিংস", "loading": "লোড হচ্ছে…", "search": "অনুসন্ধান", "retry": "আবার চেষ্টা"},
        "navigation": {"home": "হোম", "director": "পরিচালক", "editor": "সম্পাদক", "bible": "প্রোডাকশন বাইবেল", "jobs": "জবস", "coDirector": "সহ-পরিচালক", "settings": "সেটিংস"},
        "settings": {"title": "সেটিংস", "interfaceLanguage": "ইন্টারফেস ভাষা", "conversationLanguage": "সহ-পরিচালকের কথোপকথন ভাষা", "languageHelp": "ইন্টারফেস ভাষা প্রকল্পের সঠিক ভাষা পরিবর্তন করে না।"},
        "errors": {"generic": "কিছু ভুল হয়েছে।", "modelKnowledgeUnavailable": "নির্বাচিত মডেলের জ্ঞান উপলব্ধ নয়।", "translationFailed": "অনুবাদ ব্যর্থ। মূল পাঠ্য সংরক্ষিত।"},
        "jobs": {"title": "জবস", "failed": "জব {{jobName}} ব্যর্থ", "running": "চলছে", "succeeded": "সফল"},
        "codirector": {"title": "সহ-পরিচালক", "placeholder": "আপনার সৃজনশীল অভিপ্রায় লিখুন…", "send": "পাঠান", "recommendedModel": "প্রস্তাবিত মডেল"},
    },
    "id": {
        "common": {"save": "Simpan", "cancel": "Batal", "close": "Tutup", "language": "Bahasa", "settings": "Pengaturan", "loading": "Memuat…", "search": "Cari", "retry": "Coba lagi"},
        "navigation": {"home": "Beranda", "director": "Sutradara", "editor": "Editor", "bible": "Alkitab Produksi", "jobs": "Pekerjaan", "coDirector": "Co-Director", "settings": "Pengaturan"},
        "settings": {"title": "Pengaturan", "interfaceLanguage": "Bahasa antarmuka", "conversationLanguage": "Bahasa percakapan Co-Director", "languageHelp": "Bahasa antarmuka tidak mengubah bahasa kanonik proyek."},
        "errors": {"generic": "Terjadi kesalahan.", "modelKnowledgeUnavailable": "Pengetahuan model tidak tersedia.", "translationFailed": "Terjemahan gagal. Teks asli dipertahankan.", "recoveryHint": "Coba lagi atau pulihkan pekerjaan dari Pekerjaan."},
        "jobs": {"title": "Pekerjaan", "failed": "Pekerjaan {{jobName}} gagal", "running": "Berjalan", "succeeded": "Berhasil"},
        "codirector": {"title": "Co-Director", "placeholder": "Jelaskan niat kreatif Anda…", "send": "Kirim", "recommendedModel": "Model yang direkomendasikan"},
    },
    "ur": {
        "common": {"save": "محفوظ کریں", "cancel": "منسوخ", "close": "بند کریں", "language": "زبان", "settings": "ترتیبات", "loading": "لوڈ ہو رہا ہے…", "search": "تلاش", "retry": "دوبارہ کوشش"},
        "navigation": {"home": "ہوم", "director": "ڈائریکٹر", "editor": "ایڈیٹر", "bible": "پروڈکشن بائبل", "jobs": "جابات", "coDirector": "شریک ڈائریکٹر", "settings": "ترتیبات"},
        "settings": {"title": "ترتیبات", "interfaceLanguage": "انٹرفیس زبان", "conversationLanguage": "شریک ڈائریکٹر گفتگو کی زبان", "languageHelp": "انٹرفیس زبان پروجیکٹ کی قانونی زبان نہیں بدلتی۔", "rtlNote": "عربی اور اردو دائیں سے بائیں لے آؤٹ استعمال کرتے ہیں۔"},
        "errors": {"generic": "کچھ غلط ہو گیا۔", "modelKnowledgeUnavailable": "منتخب ماڈل کا علم دستیاب نہیں۔", "translationFailed": "ترجمہ ناکام۔ اصل متن محفوظ رکھا گیا۔"},
        "jobs": {"title": "جابات", "failed": "جاب {{jobName}} ناکام", "running": "چل رہا ہے", "succeeded": "کامیاب"},
        "codirector": {"title": "شریک ڈائریکٹر", "placeholder": "اپنا تخلیقی ارادہ بیان کریں…", "send": "بھیجیں", "recommendedModel": "تجویز کردہ ماڈل"},
    },
}


def write_locales() -> None:
    WEB_I18N.mkdir(parents=True, exist_ok=True)
    (WEB_I18N / "locales").mkdir(exist_ok=True)
    for code, *_ in LOCALES:
        data = deep_fill(code)
        if code in COMPACT:
            for ns, keys in COMPACT[code].items():
                data.setdefault(ns, {}).update(keys)
        loc_dir = WEB_I18N / "locales" / code
        loc_dir.mkdir(parents=True, exist_ok=True)
        for ns in NAMESPACES:
            payload = data.get(ns) or EN.get(ns, {})
            (loc_dir / f"{ns}.json").write_text(
                json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
    meta = {
        "locales": [
            {
                "locale": c,
                "displayName": d,
                "nativeName": n,
                "direction": direction,
                "fallback": "en",
                "enabled": True,
                "status": status,
                "reviewLevel": review,
                "dateLocale": date_l,
                "numberLocale": num_l,
                "notes": "Portuguese uses Brazilian Portuguese (pt-BR) conventions." if c == "pt" else "",
            }
            for c, d, n, direction, date_l, num_l, status, review in LOCALES
        ],
        "namespaces": NAMESPACES,
        "betaCriticalNamespaces": [
            "common",
            "navigation",
            "codirector",
            "production-bible",
            "director",
            "editor",
            "jobs",
            "errors",
            "settings",
            "accessibility",
            "approval",
            "export",
        ],
    }
    (WEB_I18N / "locale-meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Wrote locales under {WEB_I18N / 'locales'}")


def main() -> None:
    write_locales()
    DOCS.mkdir(parents=True, exist_ok=True)
    print("OK")


if __name__ == "__main__":
    main()
