"""Canonical dotted tool IDs → stable snake_case (or existing) registry IDs.

Aliases resolve before lookup so both IDs share the same handler binding.
New Wave 3 tools may use dotted IDs as their primary `tool_id`.
"""

from __future__ import annotations

# Canonical (preferred in prompts) → primary registry tool_id
CANONICAL_ALIASES: dict[str, str] = {
    "project.get_summary": "project.get_summary",
    "project.list_blockers": "project.list_blockers",
    "script.list": "script.list",
    "script.get": "script.get",
    "script.search": "script.search",
    "script.inspect": "script.inspect",
    "script.scene_context": "script.scene_context",
    "script.character_context": "script.character_context",
    "script.analyze_structure": "script.analyze_structure",
    "script.analyze_scene": "script.analyze_scene",
    "script.analyze_dialogue": "script.analyze_dialogue",
    "script.analyze_continuity": "script.analyze_continuity",
    "script.suggest_revision": "script.suggest_revision",
    "script.generate_outline": "script.generate_outline",
    "script.generate_beat_sheet": "script.generate_beat_sheet",
    "script.propose_insert": "script.propose_insert",
    "script.propose_replace": "script.propose_replace",
    "script.propose_delete": "script.propose_delete",
    "script.propose_scene": "script.propose_scene",
    "script.convert_outline_to_scenes": "script.convert_outline_to_scenes",
    "script.sync_production_bible": "script.sync_production_bible",
    "script.prepare_timeline": "script.prepare_timeline",
    "runtime.list": "runtime.list",
    "runtime.inspect": "runtime.inspect",
    "runtime.test": "runtime.test",
    
    "runtime.preview_install": "runtime.preview_install",
    "runtime.install": "runtime.install",
    "runtime.preview_update": "runtime.preview_update",
    "runtime.update": "runtime.update",
    "runtime.preview_repair": "runtime.preview_repair",
    "runtime.repair": "runtime.repair",
    "runtime.preview_uninstall": "runtime.preview_uninstall",
    "runtime.uninstall": "runtime.uninstall",
    "runtime.start": "runtime.start",
    "runtime.stop": "runtime.stop",
    "runtime.restart": "runtime.restart",
    "scene.list": "list_scenes",
    "scene.get": "get_scene",
    "scene.search": "scene.search",
    "scene.list_characters": "scene.list_characters",
    "scene.list_assets": "scene.list_assets",
    "character.list": "list_character_profiles",
    "character.get": "inspect_character_profile",
    "character.search": "character.search",
    "production_bible.get_summary": "get_production_bible_summary",
    "production_bible.list_entries": "list_bible_entities",
    "production_bible.get_entry": "get_bible_entity",
    "production_bible.search": "production_bible.search",
    "asset.list": "search_library_assets",
    "asset.get": "asset.get",
    "asset.search": "search_library_assets",
    "asset.list_by_scene": "scene.list_assets",
    "asset.list_by_character": "asset.list_by_character",
    "production_plan.list": "production_plan.list",
    "production_plan.get": "production_plan.get",
    "production_plan.get_version": "production_plan.get_version",
    "production_plan.list_versions": "production_plan.list_versions",
    "production_plan.list_events": "production_plan.list_events",
    "production_plan.validate": "production_plan.validate",
    "production_plan.get_readiness": "production_plan.get_readiness",
    "production_plan.create_draft": "production_plan.create_draft",
    "production_plan.propose": "production_plan.propose",
    "production_plan.approve": "production_plan.approve",
    "production_plan.reject": "production_plan.reject",
    "production_plan.revise": "production_plan.revise",
    "production_plan.pause": "production_plan.pause",
    "production_plan.resume": "production_plan.resume",
    "production_plan.cancel": "production_plan.cancel",
    "production_plan.archive": "production_plan.archive",
    "production_plan.resolve_blocker": "production_plan.resolve_blocker",
    "proposal.list": "proposal.list",
    "proposal.get": "proposal.get",
    "job.list": "job.list",
    "job.get": "job.get",
    "continuity.list_findings": "continuity.list_findings",
    "continuity.get_finding": "continuity.get_finding",
    "workspace.get_active_context": "workspace.get_active_context",
    "system.list_capabilities": "system.list_capabilities",
}


def resolve_tool_id(tool_id: str) -> str:
    return CANONICAL_ALIASES.get(tool_id, tool_id)
